<?php

return [

    'accepted' => ':attribute muss akzeptiert werden.',
    'active_url' => ':attribute ist keine gültige URL..',
    'after' => ':attribute muss ein Datum sein, das nach :date.',
    'after_or_equal' => ':attribute muss ein Datum sein, das nach oder gleich dem :date ist.',
    'alpha' => ' :attribute darf nur Buchstaben enthalten.',
    'alpha_dash' => ':attribute darf nur Buchstaben, Zahlen und Bindestriche enthalten.',
    'alpha_num' => ':attribute darf nur Buchstaben und Zahlen enthalten.',
    'array' => ':attribute muss ein Array sein.',
    'before' => ':attribute muss ein Datum sein, das vor :date ist.',
    'before_or_equal' => ':attribute muss ein Datum sein, das vor oder gleich dem :date ist.',
    'between' => [
        'numeric' => ':attribute muss zwischen :min und :max liegen.',
        'file' => ':attribute muss zwischen :min und :max Kilobytes liegen.',
        'string' => ':attribute muss zwischen :min und :max Zeichen liegen.',
        'array' => ':attribute muss zwischen :min und :max Einträge liegen.',
    ],
    'boolean' => ':attribute Feld muss true oder false sein.',
    'confirmed' => ':attribute Bestätigung stimmt nicht überein.',
    'date' => ':attribute ist kein gültiges Datum.',
    'date_format' => ':attribute entspricht nicht dem Format :format.',
    'different' => ':attribute und :other müssen unterschiedlich sein.',
    'digits' => ':attribute muss :digits Ziffern.',
    'digits_between' => ':attribute muss zwischen :min und :max Ziffern sein.',
    'dimensions' => ':attribute hat ungültige Bildmaße.',
    'distinct' => ':attribute Feld hat einen doppelten Wert.',
    'email' => ':attribute muss eine gültige E-Mail Adresse sein.',
    'exists' => 'ausgewählte :attribute ist ungültig.',
    'file' => ':attribute muss eine Datei sein.',
    'filled' => ':attribute Feld ist erforderlich.',
    'image' => ':attribute muss ein Bild sein.',
    'in' => 'ausgewählte :attribute ist ungültig.',
    'in_array' => 'Das Feld :attribute existiert nicht in :other',
    'integer' => ':attribute muss eine ganze Zahl sein..',
    'ip' => ':attribute muss eine gültige IP-Adresse sein.',
    'json' => ':attribute muss ein gültiger JSON-String sein.',
    'max' => [
        'numeric' => ':attribute darf nicht größer sein als :max.',
        'file' => ':attribute darf nicht größer sein als :max Kilobytes.',
        'string' => ':attribute darf nicht größer sein als :max Zeichen.',
        'array' => ':attribute darf nicht größer sein als :max Einträge.',
    ],
    'mimes' => ':attribute muss eine Datei des Typs :values sein.',
    'mimetypes' => ':attribute muss eine Datei des Typs :values.',
    'min' => [
        'numeric' => ':attribute muss mindestens :min sein.',
        'file' => ':attribute muss mindestens :min Kilobytes sein.',
        'string' => ':attribute muss mindestens :min Zeichen sein.',
        'array' => ':attribute muss mindestens :min Einträge sein.',
    ],
    'not_in' => 'ausgewählte :attribute ist ungültig.',
    'numeric' => ':attribute muss eine Zahl sein.',
    'present' => ':attribute Feld muss vorhanden sein.',
    'regex' => ':attribute Format ist ungültig.',
    'required' => ':attribute Feld ist erforderlich.',
    'required_if' => ':attribute Feld ist erforderlich, wenn :other :value ist.',
    'required_unless' => ':attribute ist ein Pflichtfeld, es sei denn :other ist :values.',
    'required_with' => ':attribute Feld ist erforderlich, wenn :values vorhanden ist.',
    'required_with_all' => ':attribute Feld ist erforderlich, wenn :values vorhanden ist.',
    'required_without' => ':attribute Feld ist erforderlich, wenn :values nicht vorhanden ist.',
    'required_without_all' => ':attribute Feld ist erforderlich, wenn keine :values vorhanden ist.',
    'same' => ':attribute und :other muss übereinstimmen.',
    'size' => [
        'numeric' => ':attribute muss :size sein.',
        'file' => ':attribute muss :size Kilobytes sein.',
        'string' => ':attribute muss :size Zeichen sein.',
        'array' => ':attribute must contain :size Einträge sein.',
    ],
    'string' => ':attribute muss eine Zeichenkette sein.',
    'timezone' => ':attribute muss ein gültiger Bereich sein.',
    'unique' => ':attribute ist bereits vergeben.',
    'uploaded' => ':attribute Hochladen fehlgeschlagen.',
    'url' => ':attribute Format ist ungültig.',

    'attributes' => [],
];
