<?php

return [
    'accepted' => ':attribute мусить бути прийнято.',
    'active_url' => ':attribute не є дійсною URL-адресою.',
    'after' => ':attribute мусить бути датою після :date.',
    'after_or_equal' => ':attribute мусить бути датою після або рівною :date.',
    'alpha' => ':attribute може містити лише літери.',
    'alpha_dash' => ':attribute може містити лише літери, числа та дефіси.',
    'alpha_num' => ':attribute може містити лише літери та числа.',
    'array' => ':attribute мусить бути масивом.',
    'before' => ':attribute мусить бути датою до :date.',
    'before_or_equal' => ':attribute мусить бути датою до або рівною :date.',
    'between' => [
        'numeric' => ':attribute мусить бути між :min та :max.',
        'file' => ':attribute мусить бути між :min та :max кілобайт.',
        'string' => ':attribute мусить бути між :min та :max символами.',
        'array' => ':attribute мусить містити між :min та :max елементами.',
    ],
    'boolean' => 'Поле :attribute мусить бути істинним або хибним.',
    'confirmed' => 'Підтвердження :attribute не співпадає.',
    'date' => ':attribute не є дійсною датою.',
    'date_format' => ':attribute не відповідає формату :format.',
    'different' => ':attribute та :other мають бути різними.',
    'digits' => ':attribute мусить складатися з :digits цифр.',
    'digits_between' => ':attribute мусить бути між :min та :max цифрами.',
    'dimensions' => ':attribute має недійсні розміри зображення.',
    'distinct' => 'Поле :attribute має повторюване значення.',
    'email' => ':attribute мусить бути дійсною електронною адресою.',
    'exists' => 'Вибране :attribute недійсне.',
    'file' => ':attribute мусить бути файлом.',
    'filled' => 'Поле :attribute обов\'язкове для заповнення.',
    'image' => ':attribute мусить бути зображенням.',
    'in' => 'Вибране :attribute недійсне.',
    'in_array' => 'Поле :attribute не існує в :other.',
    'integer' => ':attribute мусить бути цілим числом.',
    'ip' => ':attribute мусить бути дійсною IP-адресою.',
    'json' => ':attribute мусить бути дійсним JSON-рядком.',
    'max' => [
        'numeric' => ':attribute не може бути більше :max.',
        'file' => ':attribute не може бути більше :max кілобайт.',
        'string' => ':attribute не може бути більше :max символів.',
        'array' => ':attribute не може містити більше :max елементів.',
    ],
    'mimes' => ':attribute мусить бути файлом типу: :values.',
    'mimetypes' => ':attribute мусить бути файлом типу: :values.',
    'min' => [
        'numeric' => ':attribute мусить бути щонайменше :min.',
        'file' => ':attribute мусить бути щонайменше :min кілобайт.',
        'string' => ':attribute мусить бути щонайменше :min символів.',
        'array' => ':attribute мусить містити щонайменше :min елементів.',
    ],
    'not_in' => 'Вибране :attribute недійсне.',
    'numeric' => ':attribute мусить бути числом.',
    'present' => 'Поле :attribute мусить бути присутнім.',
    'regex' => 'Формат :attribute недійсний.',
    'required' => 'Поле :attribute обов\'язкове для заповнення.',
    'required_if' => 'Поле :attribute обов\'язкове для заповнення, коли :other є :value.',
    'required_unless' => 'Поле :attribute обов\'язкове для заповнення, якщо :other не є в :values.',
    'required_with' => 'Поле :attribute обов\'язкове для заповнення, коли присутні :values.',
    'required_with_all' => 'Поле :attribute обов\'язкове для заповнення, коли присутні :values.',
    'required_without' => 'Поле :attribute обов\'язкове для заповнення, коли :values відсутні.',
    'required_without_all' => 'Поле :attribute обов\'язкове для заповнення, коли жодне з :values не присутнє.',
    'same' => ':attribute та :other мають співпадати.',
    'size' => [
        'numeric' => ':attribute мусить бути :size.',
        'file' => ':attribute мусить бути :size кілобайт.',
        'string' => ':attribute мусить бути :size символів.',
        'array' => ':attribute мусить містити :size елементів.',
    ],
    'string' => ':attribute мусить бути рядком.',
    'timezone' => ':attribute мусить бути дійсною зоною.',
    'unique' => ':attribute вже використовується.',
    'uploaded' => ':attribute не вдалося завантажити.',
    'url' => 'Формат :attribute недійсний.',

    'attributes' => [],
];
