<?php

return [
    'accepted' => 'Поле :attribute повинно бути прийняте.',
    'active_url' => 'Поле :attribute не є дійсним URL.',
    'after' => 'Поле :attribute повинно бути датою після :date.',
    'after_or_equal' => 'Поле :attribute повинно бути датою після або рівною :date.',
    'alpha' => 'Поле :attribute може містити лише літери.',
    'alpha_dash' => 'Поле :attribute може містити лише літери, цифри та дефіси.',
    'alpha_num' => 'Поле :attribute може містити лише літери та цифри.',
    'array' => 'Поле :attribute повинно бути масивом.',
    'before' => 'Поле :attribute повинно бути датою перед :date.',
    'before_or_equal' => 'Поле :attribute повинно бути датою перед або рівною :date.',
    'between' => [
        'numeric' => 'Поле :attribute повинно бути між :min і :max.',
        'file' => 'Поле :attribute повинно бути між :min і :max кілобайтами.',
        'string' => 'Поле :attribute повинно бути між :min і :max символами.',
        'array' => 'Поле :attribute повинно містити від :min до :max елементів.',
    ],
    'boolean' => 'Поле :attribute повинно бути true або false.',
    'confirmed' => 'Поле :attribute не співпадає з підтвердженням.',
    'date' => 'Поле :attribute не є дійсною датою.',
    'date_format' => 'Поле :attribute не відповідає формату :format.',
    'different' => 'Поля :attribute і :other повинні бути різними.',
    'digits' => 'Поле :attribute повинно бути довжиною :digits цифр.',
    'digits_between' => 'Поле :attribute повинно бути між :min і :max цифрами.',
    'dimensions' => 'Поле :attribute містить недійсні розміри зображення.',
    'distinct' => 'Поле :attribute має повторюючеся значення.',
    'email' => 'Поле :attribute повинно бути дійсною електронною адресою.',
    'exists' => 'Вибране поле :attribute недійсне.',
    'file' => 'Поле :attribute повинно бути файлом.',
    'filled' => 'Поле :attribute обов\'язкове для заповнення.',
    'image' => 'Поле :attribute повинно бути зображенням.',
    'in' => 'Вибране поле :attribute недійсне.',
    'in_array' => 'Поле :attribute не існує в :other.',
    'integer' => 'Поле :attribute повинно бути цілим числом.',
    'ip' => 'Поле :attribute повинно бути дійсною IP-адресою.',
    'json' => 'Поле :attribute повинно бути дійсним JSON-рядком.',
    'max' => [
        'numeric' => 'Поле :attribute не може бути більше :max.',
        'file' => 'Поле :attribute не може бути більше :max кілобайтів.',
        'string' => 'Поле :attribute не може бути більше :max символів.',
        'array' => 'Поле :attribute не може мати більше :max елементів.',
    ],
    'mimes' => 'Поле :attribute повинно бути файлом типу: :values.',
    'mimetypes' => 'Поле :attribute повинно бути файлом типу: :values.',
    'min' => [
        'numeric' => 'Поле :attribute повинно бути не менше :min.',
        'file' => 'Поле :attribute повинно бути не менше :min кілобайтів.',
        'string' => 'Поле :attribute повинно містити принаймні :min символів.',
        'array' => 'Поле :attribute повинно містити принаймні :min елементів.',
    ],
    'not_in' => 'Вибране поле :attribute недійсне.',
    'numeric' => 'Поле :attribute повинно бути числом.',
    'present' => 'Поле :attribute повинно бути присутнім.',
    'regex' => 'Формат поля :attribute недійсний.',
    'required' => 'Поле :attribute обов\'язкове для заповнення.',
    'required_if' => 'Поле :attribute є обов\'язковим, коли :other дорівнює :value.',
    'required_unless' => 'Поле :attribute є обов\'язковим, якщо :other не знаходиться в :values.',
    'required_with' => 'Поле :attribute є обов\'язковим, якщо присутній :values.',
    'required_with_all' => 'Поле :attribute є обов\'язковим, якщо присутні :values.',
    'required_without' => 'Поле :attribute є обов\'язковим, якщо відсутні :values.',
    'required_without_all' => 'Поле :attribute є обов\'язковим, якщо жодне з :values не присутні.',
    'same' => 'Поля :attribute і :other повинні збігатися.',
    'size' => [
        'numeric' => 'Поле :attribute повинно бути розміру :size.',
        'file' => 'Поле :attribute повинно бути розміру :size кілобайт.',
        'string' => 'Поле :attribute повинно містити :size символів.',
        'array' => 'Поле :attribute повинно містити :size елементів.',
    ],
    'string' => 'Поле :attribute повинно бути рядком.',
    'timezone' => 'Поле :attribute повинно бути дійсним часовим поясом.',
    'unique' => 'Таке значення поля :attribute вже існує.',
    'uploaded' => 'Не вдалося завантажити поле :attribute.',
    'url' => 'Формат поля :attribute недійсний.',

    'attributes' => [],

    'internal' => [
        'variable_value' => 'змінна :env',
        'invalid_password' => 'Наданий пароль є недійсним для цього облікового запису.',
    ],
];
