<?php

return [
    'accepted' => ':Atributul trebuie acceptat.',
    'active_url' => ':Atributul nu este un URL valabil.',
    'after' => ':Atributul trebuie să fie o dată după :dată.',
    'after_or_equal' => ':attribute trebuie să fie o dată după sau egală cu :date.',
    'alpha' => ':Atributul poate conține numai litere.',
    'alpha_dash' => ':Atributul poate conține numai litere, cifre și liniuțe.',
    'alpha_num' => ':Atributul poate conține numai litere și cifre.',
    'array' => ':Atributul trebuie să fie o serie.',
    'before' => ':Atributul trebuie să fie o dată înainte de :dată.',
    'before_or_equal' => ':attribute trebuie să fie o dată anterioară sau egală cu: date.',
    'between' => [
        'numeric' => ':attribute trebuie să fie între :min și :max.',
        'file' => ':attribute  trebuie să aibă între :min și :max kilobytes.',
        'string' => ':attribute trebuie să aibă între :min și :max caractere.',
        'array' => ':attribute trebuie să aibă între :min și :max elemente.',
    ],
    'boolean' => 'Câmpul :atributului trebuie să fie adevărat sau fals.',
    'confirmed' => 'Confirmarea :atributului nu se potrivește.',
    'date' => ':Atributul nu este o dată valabilă.',
    'date_format' => ':Atributul nu se potrivește formatului :format.',
    'different' => ':Atributul și :celălalt trebuie să fie diferite.',
    'digits' => ':Atributul trebuie să fie :cifre cifre.',
    'digits_between' => ':Atributul trebuie să fie între cifra :min și :max.',
    'dimensions' => ':Atributul are dimensiuni ale imaginii nevalide.',
    'distinct' => 'Câmpul :atribut are o valoare duplicat.',
    'email' => ':Atributul trebuie să fie o adresă de e-mail valabilă.',
    'exists' => ':attribute selectat nu este valid.',
    'file' => ':attribute trebuie să fie un fișier.',
    'filled' => 'Câmpul :atribut este necesar.',
    'image' => ':attribute trebuie să fie o imagine.',
    'in' => ':attribute selectat nu este valid.',
    'in_array' => 'Câmpul :atribut nu există în :celelalte.',
    'integer' => ':Atributul trebuie să fie un număr întreg.',
    'ip' => ':Atributul trebuie să fie o adresă IP valabilă.',
    'json' => ':Atributul trebuie să fie un șir JSON valabil.',
    'max' => [
        'numeric' => ':attribute nu poate fi mai mare decât :max.',
        'file' => ':attribute nu poate fi mai mare de :max kilobytes.',
        'string' => ':attribute nu poate fi mai mare de :max caractere.',
        'array' => ':attribute nu poate avea mai mult de :max articole.',
    ],
    'mimes' => ':Atributul trebuie să fie un fișier de tipul: :valori.',
    'mimetypes' => ':Atributul trebuie să fie un fișier de tipul: :valori.',
    'min' => [
        'numeric' => ':attribute trebuie să fie cel puțin :min.',
        'file' => ':attribute trebuie să aibă cel puțin :min kilobytes.',
        'string' => ':attribute trebuie să aibă cel puțin :length caractere.',
        'array' => ':attribute trebuie să aibă cel puțin :min elemente.',
    ],
    'not_in' => ':attribute selectat nu este valid.',
    'numeric' => ':Atributul trebuie să fie un număr.',
    'present' => 'Câmpul :atribut trebuie să existe.',
    'regex' => 'Formatul :atribut nu este valabil.',
    'required' => 'Câmpul :atribut este necesar.',
    'required_if' => 'Câmpul :atribut este necesar când :celelalte este :valoare.',
    'required_unless' => 'Câmpul :atribut este necesar cu excepția cazului când :celelalte este în :valori.',
    'required_with' => 'Câmpul :atribut este necesar când există :valori.',
    'required_with_all' => 'Câmpul :atribut este necesar când există :valori.',
    'required_without' => 'Câmpul :atribut este necesar când nu există :valori.',
    'required_without_all' => 'Câmpul :atribut este necesar când nu există niciuna dintre :valori.',
    'same' => ':Atributul și :celelalte trebuie să se potrivească.',
    'size' => [
        'numeric' => ':attribute trebuie să fie :size.',
        'file' => ':attribute trebuie să aibă :size kilobytes.',
        'string' => ':attribute trebuie să aibă :size caractere.',
        'array' => ':attribute trebuie să conțină :size elemente.',
    ],
    'string' => ':Atributul trebuie să fie un șir.',
    'timezone' => ':Atributul trebuie să fie o zonă valabilă.',
    'unique' => ':attribute a fost deja luat.',
    'uploaded' => ':attribute nu s-a încărcat.',
    'url' => 'Formatul :atribut nu este valabil.',
];
