<?php

return [
    'choose_domain' => 'ایک ڈومین منتخب کریں...',
    'reg_new_domain' => 'نیا ڈومین رجسٹر کریں',
    'use_own_domain' => 'اپنا خود کا ڈومین استعمال کریں',
    'description' => 'تفصیل',
    'balance_before_transaction' => 'تراکیب سے پہلے بیلنس',
    'amount' => 'رقم',
    'date' => 'تاریخ',
    'your_services' => 'آپ کی خدمات',
    'results' => 'نتائج',
    'more_info' => 'مزید معلومات',
    'showing' => 'دکھا رہا ہے: :count کا :all نتائج',
    'add_balance' => 'بیلنس شامل کریں',
    'order_new_service' => 'نیا سروس آرڈر کریں',
    'terminated' => 'منسلک ہوگئی',
    'cancelled' => 'منسلک ہوگئی',
    'expand_collapse_row' => 'قطار کو بڑھائیں/گھٹائیں',
    'product' => 'پروڈکٹ',
    'service' => 'سروس',
    'category' => 'قسم',
    'status' => 'حالت',
    'details' => 'تفصیلات',
    'package' => 'پیکج',
    'billing_cycle' => 'بلنگ سائیکل',
    'due_date' => 'آخری تاریخ',
    'last_renewal_date' => 'آخری تجدید کی تاریخ',
    'next_invoice' => 'اگلا انوائس',
    'no_orders_found' => 'کوئی آرڈرز نہیں ملے',
    'no_orders_found_desc' => 'آپ نے ابھی تک کوئی آرڈر نہیں کیا ہے، نئے آرڈرز یہاں دکھائیں گے۔',
    'paid' => 'ادا کردیا گیا',

    'unpaid' => 'ادا نہیں ہوا',
    'refunded' => 'واپسی ہوگئی',
    'actions' => 'عمل',
    'no_records_found' => 'کوئی ریکارڈ نہیں ملا',
    'no_records_found_description' => 'آپ کوئی :object نہیں ہے، نیا :object یہاں دکھایا جائے گا',
    'no_record_found_desc' => 'آپ نے ابھی تک کوئی انوائس :paid نہیں کی ہے، :paid انوائس یہاں دکھائی جائے گی',
    'invoice' => 'انوائس',
    'payment_not_received' => 'ادائیگی ابھی تک ملی نہیں ہے۔',
    'checking_in' => 'چیک ان',
    'bitpave_payment_engine' => 'بٹ پیو ڈ پیمنٹ انجن',
    'payment_details' => 'ادائیگی کی تفصیلات',
    'payment_total_is' => 'آپ کی کل ادائیگی $:is ہے،:for کے لئے',
    'bitpave_instruction' => '1. اپنے بٹ کوئن والٹ ایپ کو کھولیں یا QR کوڈ اسکین کریں<br>
                       2. <u>بالکل</u> <strong>:price</strong> BTC کو
                       <strong>:wallet</strong> بھیجیں<br>
                       3. آپ کا کام ہو گیا 🚀 🙌',
    'wallet' => 'والٹ',
    'bitcoin_amount' => 'بٹ کوئن کی رقم',
    'awaiting_payment' => 'ادائیگی کا منتظر ہونا...',
    'session_expired' => 'سیشن ختم ہو گیا',
    'copied' => 'کاپی کیا گیا',
    'scanning_payments' => 'ادائیگیوں کا اسکین کرنا',
    'stripe_card_payment' => 'اسٹرائپ کارڈ ادائیگی',
    'credit_debit_card' => 'کریڈٹ یا ڈیبٹ کارڈ',
    'submit_payment' => 'ادائیگی جمع کروائیں',
    'provide_missing_information' => 'نا مکمل معلومات فراہم کریں',
    'provide_missing_information_desc' => 'ہمیں پتہ وغیرہ جیسی معلومات جمع کرنی ہے۔ براہ کرم کرکے فارم مکمل کریں تاکہ آپ جاری رہ سکیں۔',
    'optional' => '(اختیاری)',
    'organization' => 'تنظیم',
    'company_name' => 'کمپنی کا نام',

    'select_an_option' => 'ایک اختیار منتخب کریں',
    'address' => 'پتہ',
    'city' => 'شہر',
    'zip_code' => 'زپ کوڈ',
    'state_region_provice' => 'ریاست / علاقہ / صوبہ',
    'region' => 'علاقہ',
    'save_all' => 'سب کچھ محفوظ کریں',
    'info' => 'معلومات',
    'unpaid_warn' => 'آپ کے پاس <span class="font-medium">:count</span> ادا نہیں ہوئی انوائس ہیں۔ انہیں وقت پر ادا کریں تاکہ آپ کی سروس میں کسی بھی رکاوٹ سے بچایا جا سکے۔',
    'services' => 'سروسز',
    'invoices' => 'انوائس',
    'balance' => 'بیلنس',
    'change_color' => 'رنگ تبدیل کریں',
    'customize_your_preference' => 'اپنی ترجیح کے مطابق ترتیب دیں',
    'rose' => 'روز',
    'pink' => 'گلابی',
    'fuchsia' => 'فوشیا',
    'purple' => 'جامنی',
    'violet' => 'وائیولیٹ',
    'indigo' => 'انڈیگو',
    'blue' => 'نیلا',
    'sky' => 'آسمانی',
    'cyan' => 'سائن',
    'teal' => 'ٹیل',
    'emerald' => 'ایمرلڈ',
    'green' => 'سبز',
    'lime' => 'لائم',
    'yellow' => 'زرد',
    'amber' => 'ایمبر',
    'orange' => 'نارنجی',
    'red' => 'سرخ',
    'stone' => 'پتھر',
    'neutral' => 'نیوٹرل',
    'zinc' => 'زنک',
    'gray' => 'سرمئی',
    'slate' => 'سلیٹ',
    'login' => 'لاگ ان',
    'view_notifications' => 'اطلاعات دیکھیں',
    'notifications' => 'اطلاعات',
    'icon_description' => 'آئیکن کی تفصیل',
    'mark_as_read' => 'پڑھا گیا مارک کریں',
    'email_history' => 'ای میل ہسٹری',
    'invoice_history' => 'انوائس ہسٹری',
    'apps' => 'ایپس',

    'open_user_menu' => 'صارف کا مینو کھولیں',
    'account_settings' => 'اکاؤنٹ کی ترتیبات',
    'online' => 'آن لائن',
    'away' => 'دور',
    'busy' => 'مصروف',
    'appear_offline' => 'آف لائن نظر آئیں',
    'subscriptions' => 'سبسکرائب کریں',
    'admin' => 'ایڈمن',
    'sign_out' => 'باہر نکلیں',
    'last_login_at' => 'آخری لاگ ان ہوا تھا',
    'never' => 'کبھی نہیں',
    'member_since' => 'سے ممبر',
    'visibility' => 'نمائش',
    'update' => 'اپ ڈیٹ',
    'upgrade' => 'اپگریڈ',
    'upgrade_now' => 'اب اپگریڈ کریں',
    'upgrade_current_package_to_category' => 'اپنے موجودہ پیکیج :package کو نئے پیکیج کی طرف اپگریڈ کریں',
    'current_package' => 'موجودہ پیکیج',
    'price_cycle' => 'قیمت چکر',
    'change_price_cycle' => 'قیمت چکر تبدیل کریں',
    'cycle' => 'چکر',
    'cancellation_fee' => 'منسوخ کرنے کی فیس',
    'upgrade_price_info' => 'یہ خدمت :days دنوں میں ختم ہو گئی ہے۔ آپ فوراً <span id="selected_package2">:package</span> میں اپ گریڈ ہو جائیں گے اور باقی دنوں کے لئے فرق کی فیس چارج ہو گی',
    'dashboard' => 'ڈیش بورڈ',
    'store' => 'اسٹور',
    'view_all' => 'سب دیکھیں',
    'maintenance_mode_enabled' => 'میینٹیننس موڈ چالو ہے',
    'maintenance_mode_desc' => 'اس پینل کو میینٹیننس موڈ چالو ہو گیا ہے تو صارفین کے لئے یہ حالت موقتاً دستیاب نہیں ہوتی ہے۔ آپ مومنٹننس موڈ کو چھوڑ رہے ہیں۔',
    'disable_maintenance' => 'مینٹیننس غیر فعال کریں',
    'dismiss' => 'رد کریں',
    'view_all_services' => 'تمام خدمات دیکھیں',
    'close_menu' => 'مینو بند کریں',
    'balance_sidebar_desc' => 'ایک بار ادا کرنے کے بعد، آپ نے جتنا منتخب کیا ہے وہ رقم آپ کے اکاؤنٹ بیلنس میں جمع ہو جائے گی، جس سے آپ اپنی خدمات کو دوبارہ نیا کر سکتے ہیں یا نئے آرڈر دے سکتے ہیں۔',
    'balance_how_add' => 'آپ کتنا شامل کرنا چاہتے ہیں؟',
    'pay_now' => 'اب ادا کریں',

    'help_center' => 'مدد کا مرکز',
    'resources' => 'وسائل',
    'legal' => 'قانونی',
    'all_rights_reserved' => 'تمام حقوق محفوظ ہیں۔',
    'price_block_desc' => 'پہلے :period :total_price پھر ہر :per_period کے لئے :renewal_price',
    'price_onetime_block_desc' => 'آپ ایک دفعہ :price ادا کرتے ہیں تاکہ ہمیشہ کے لئے رسائی حاصل ہو۔',
    'enter_domain' => 'ڈومین درج کریں',
    'enter_domain_desc' => 'براہ کرم درج کریں وہ ڈومین جہاں آپ یہ خدمت استعمال کرنا چاہتے ہیں۔',
    'domain' => 'ڈومین',
    'enter_domain_helper' => 'براہ کرم درست ڈومین درج کریں۔ یعنی example.com یا اگر آپ ایک ذیلی ڈومین استعمال کر رہے ہیں تو web.example.com<',
    'payment_method' => 'ادائیگی کا طریقہ',
    'payment_method_desc' => 'مطلوبہ ادائیگی کا طریقہ منتخب کریں',
    'subscription' => 'سبسکرائب',
    'custom_notes' => 'اپنی رائے',
    'custom_notes_desc' => 'آپ کسی بھی خصوصی درخواست یا ہمیں معلوم ہونا چاہئے کچھ چیزیں شامل کر سکتے ہیں۔',
    'custom_notes_placeholder' => 'یہاں اپنے خیالات لکھیں...',
    'order_summary' => 'آرڈر خلاصہ',
    'recurring' => 'دوبارہ ہونے والا',
    'due_today' => 'آج کے لئے بند ہے',
    'complete_checkout' => 'پورا چیک آؤٹ',
    'selected_price_includes_cancellation_fee' => '*منتخب قیمت چکر میں منسوخی کی فیس شامل ہے',
    'setup_fee' => 'سیٹ اپ فیس',
    'payment_canceled' => 'ادائیگی منسوخ',
    'payment_canceled_desc' => 'آپ کی ادائیگی منسوخ ہوگئی ہے، براہ کرم دوبارہ کوشش کریں۔',
    'back_dashboard' => 'ڈیش بورڈ پر واپس',
    'view_invoice' => 'انوائس دیکھیں',
    'pricing' => 'پرائسنگ',
    'pricing_for' => '>کے لئے پرائسنگ',
    'get_started' => 'شروع ہوں',
    'payment_successfully' => 'ادائیگی کامیابی سے ہوگئی',
    'payment_successfully_desc' => 'ادائیگی مکمل کرنے کا شکریہ، ہم سب کچھ آپ کے لئے تیار کر رہے ہیں۔',
    'create_subscription' => 'سبسکرائبشن بنائیں',
    'subscription_name' => 'سبسکرائبشن کا نام',
    'order' => 'آرڈر',

    'gateway' => 'گیٹ وے',
    'billed_as' => 'جیسا بل کیا گیا',
    'next_billing_date' => 'اگلا بلنگ کی تاریخ',
    'created_at' => 'تخلیق ہوئی',
    'active' => 'فعال',
    'days' => 'دن',
    'manage' => 'مینج',
    'cancel' => 'منسوخ کریں',
    'close_modal' => 'موڈل بند کریں',
    'subscription_order_desc' => 'آپ موجودہ آرڈرز کے لئے خود بخود ادائیگی کے لئے ایک سبسکرائبشن بنا سکتے ہیں جب وقت آئے۔',
    'subscription_order' => 'سبسکرائبشن آرڈر',
    'subscription_price' => 'سبسکرائبشن قیمت',
    'create' => 'بنائیں',
    'cancelling' => 'منسوخ ہو رہا ہے',
    'managing' => 'مینج ہو رہا ہے',
    'close' => 'بند کریں',
    'profile' => 'پروفائل',
    'client' => 'کلائنٹ',
    'drag_and_drop' => '<span class="font-semibold">اپ لوڈ کرنے کیلئے کلک کریں</span> یا ڈریگ اینڈ ڈراپ',
    'upload' => 'اپ لوڈ',
    'two_factor_authentication' => 'ڈو فیکٹر اتصال',
    'two_factor_authentication_desc' => 'ڈو فیکٹر اتصال آپ کے اکاؤنٹ میں مزید ایک حفاظتی پرت ڈالتا ہے جو ہونے والے وقت میں صرف پاس ورڈ کی ضرورت ہوتی ہے۔',
    'social_accounts' => 'سوشل اکاؤنٹس',
    'google_account' => 'گوگل اکاؤنٹ',
    'not_connected' => 'متصل نہیں ہے',
    'remove' => 'ہٹائیں',
    'connect' => 'ملائیں',
    'github_account' => 'گٹ ہب اکاؤنٹ',
    'discord_account' => 'ڈسکارڈ اکاؤنٹ',
    'enable' => 'فعال کریں',
    'disable' => 'غیر فعال کریں',
    'download' => 'ڈاؤن لوڈ',
    'sessions' => 'سیشنز',
    'last_seen' => 'آخری دیکھا گیا',
    'revoked' => 'واپس لے لیا گیا',
    'revoke' => 'واپس لے لو',
    'general_information' => 'عام معلومات',
    'username' => 'صارف کا نام',
    'email' => 'ای میل',
    'first_name' => 'پہلا نام',
    'subscribe_to_emails' => 'ای میلس کی سبسکرائب',
    'contact_us' => 'ہم سے رابطہ کریں',
    'contact_us_desc' => 'کیا بگ رپورٹ کرنا ہے، یا صحیح مصنوعات تلاش کرنے میں مدد چاہئے؟ ہم بہترین کوشش کریں گے کہ آپ کو جواب ملے۔',
    'subject' => 'موضوع',
    'subject_contact_us_placeholder' => 'ہمیں بتائیں کہ ہم آپ کی کس طرح مدد کرسکتے ہیں',
    'your_message' => 'آپ کا پیغام',
    'send_message' => 'پیغام بھیجیں',
    'email_history_desc' => 'آپ کے اکاؤنٹ میں بھیجے گئے تمام ای میلس کا جائزہ لیں',
    'sender' => 'بھیجنے والا',
    'address_only_vissible' => 'پتہ صرف دیکھنے والوں کے لئے ہے',
    'item' => 'آئٹم',
    'price' => 'قیمت',
    'qty' => 'مقدار',
    'discounts' => 'چھوٹ',
    'total' => 'کل',
    'subtotal' => 'ذیلی کل',
    'tax_rate' => 'ٹیکس شرح',
    'complete_payment' => 'پوری ادائیگی',
    'share' => 'شیئر',
    'sownload' => 'ڈاؤن لوڈ',
    'share_invoice_desc' => 'آپ اس انوائس کو دوسرے صارف کے ساتھ شیئر کر سکتے ہیں تاکہ وہ اسے اپنے ادائیگی گیٹ وے کے ذریعے ادا کریں۔ آپ کی پتہ تفصیلات یا پورا نام انوائس پر شیئر نہیں ہوں گے۔',
    'last_updated' => 'آخری بار اپ ڈیٹ ہوا',
    'hello' => 'ہیلو',
    'email_template_content' => 'اگر آپ کو مزید دریافتات ہیں یا مستقبل کی حمایت درکار ہے، تو براہ کرم مہربانی کر کے ہم سے ہمارے آن لائن پورٹل کے ذریعے رابطہ کریں۔ ہماری مخصوص ٹیم آپ کو ٹکٹنگ سسٹم کے ذریعے فوراً اور فعال طریقے سے مدد فراہم کرنے کے لئے دستیاب ہے۔',
    'regards' => 'شانداری',
    'email_button_desc' => 'اگر ":button" بٹن پر کلک کرنے میں مشکل ہو رہی ہے تو،
اوپر دیے گئے یو آر ایل کو اپنے ویب براؤزر میں کاپی اور پیسٹ کریں:',
    'open_main_menu' => 'مین مینو کھولیں',
    'home' => 'ہوم',
    'features' => 'خصوصیات',
    'contact' => 'رابطہ',
    'portal_redirect' => 'پورٹل ریڈائریکٹ',
    'portal_redirect_url' => 'پورٹل ریڈائریکٹ یو آر ایل',
    'portal_header_image' => 'پورٹل ہیڈر تصویر',
    'default_category' => 'ڈیفالٹ کیٹیگری',
    'submit' => 'جمع کرائیں',
    'host_favorite_games' => 'ہم آپ کے پسندیدہ کھیلوں کی ہوسٹ ہیں',
    'rust' => 'رسٹ',
    'minecraft' => 'مائنکرافٹ',
    'ack' => 'آرک: SE',

    'our_game_anel' => 'ہمارا گیم پینل',
    'our_game_anel_desc' => 'یہاں پر :app پر ہم ہوش رہتے ہیں کہ جہاں ٹیکنالوجی، نوآوری، اور سرمایہ مل کر لمبے عرصے تک قیمتی راستے کو کھولتے ہیں اور معاشرتی ترقی پیدا ہوتی ہے۔',
    'file_manager' => 'فائل منیجر',
    'file_manager_desc' => 'ہمارا فائل منیجر آپ کو آسانی سے فائلوں کو اپ لوڈ، بنائیں، ڈاؤن لوڈ، اجازتیں تعین کریں، فائلوں کو زپ اور انزپ کرنے کی اجازت دیتا ہے اور انہیں منیج کرنے میں مدد فراہم کرتا ہے۔',
    'plugins_manager' => 'پلگ ان منیجر',
    'plugins_manager_desc' => '60000 سے زائد پلگ ان میں سے چنائیں، اور صرف ایک بٹن کے کلک سے انسٹال کریں۔',
    'backup_manager' => 'بیک اپ منیجر',
    'backup_manager_desc' => 'ہمارا ڈیش بورڈ آپ کو ایک دیے گئے وقت پر آپ کی فائلوں کا بیک اپ لینے کی اجازت دیتا ہے۔',
    'user_manager' => 'صارف منیجر',
    'user_manager_desc' => 'دوستوں یا اسٹاف ممبرز کو اپنے ڈیش بورڈ پر دعوت دیں۔ آپ ہر ممبر کے لئے مخصوص اجازتیں ترتیب دے سکتے ہیں۔',
    'schedule_manager' => 'شیڈول منیجر',
    'schedule_manager_desc' => 'ہمارا شیڈول سسٹم آپ کو موقع پر پاور کنٹرولز، بیک اپ یا ٹاسکس ترتیب دینے کی اجازت دیتا ہے۔',
    'database_manager' => 'ڈیٹا بیس منیجر',
    'database_manager_desc' => 'MySQL ڈیٹا بیسیں بنائیں، نئے الاکیویشنز بنائیں اور بہت کچھ',
    'viewing_plans_for' => 'دیکھ رہے ہیں',
    'no_plans_display' => 'کوئی خراجات نہیں',
    'no_plans_display_desc' => 'آپ نے پورٹل پر ڈسپلے کرنے کے لئے کوئی منصوبے نہیں بنائے ہیں، براہ کرم شروع ہونے کے لئے منصوبے بنائیں',
    'other_categories' => 'دیگر زمرے',
    'select' => 'منتخب کریں',
    'selected' => 'منتخب ہوا',
    'get_started_now' => 'اب شروع ہو جائیں',
    'register_your_account_no-time' => 'اپنے اکاؤنٹ رجسٹر کریں اور بہت کم وقت میں اپنی سرور چلا دیں!',
    'create_my_account' => 'میرا اکاؤنٹ بنائیں',
    'try_again' => 'دوبارہ کوشش کریں',
    'please_login_to_view' => 'براہ کرم کر کے یہ صفحہ دیکھنے کے لئے لاگ ان کریں۔',
    'page_not_published' => 'صفحہ ابھی تک شائع نہیں ہوا ہے۔',
    'email_new_device_subject' => 'آپ کے :app_name اکاؤنٹ میں نیا ڈوائس وارد ہوا ہے',
    'email_check_activity_btn' => 'سرگرمی چیک کریں',
    'email_add_device_content' => '
                <br><br>
                ڈوائس کی تفصیلات: <br>
                &bull; ڈوائس: :device_name <br>
                &bull; ڈوائس ٹائپ: :device_type <br>
                &bull; آئی پی پتہ: :ip_address <br>
                &bull; آخری لاگ ان: :last_login_at <br>
                &bull; یوزر ایجنٹ: <code>:user_agent</code> <br><br>

                اگر یہ آپ نہیں تھا تو فوراً اس ڈوائس کا دستبرداری رد کریں اور ہم سے رابطہ کریں۔ ',
    'manage_service' => 'خدمت کو منظم کریں',
    'email_cancel_order_subject' => 'آپ کی خدمت منسوخ ہو گئی ہے',
    'email_cancel_order_content' => '
            <br><br>
            خدمت کی تفصیلات: <br>
            &bull; آئی ڈی: #:id <br>
            &bull; خدمت کا نام: :name <br>
            &bull; آخری مدت تک ریسٹ پراڈ: :period <br>
            &bull; منسوخ کرنے کا باعث: <code>:reason</code> <br><br>',
    'email_payment_completed_subject' => 'ادائیگی ادا ہو گئی ہے',
    'email_payment_completed_button' => 'انوائس دیکھیں',
    'email_payment_completed_content' => '                <br><br>
                ادائیگی کی تفصیلات: <br>

                &bull; ٹرانزیکشن آئی ڈی: :id <br>
                &bull; ادائیگی کی تفصیلات: :description <br>
                &bull; ادائیگی کی مقدار: :amount_rounded :currency <br>
                &bull; ادائیگی کا طریقہ: :gateway_name <br><br>

                یقینی بنیادوں پر ہے کہ آپ کی ادائیگی آپ کے اکاؤنٹ میں لاگو ہوگئی ہے، اور کسی بھی متعلقہ انوائس یا باقی رقمیں متعلقہ طور پر اپ ڈیٹ ہو گئی ہیں۔ <br>',
    'email_payment_refunded_subject' => 'ریفنڈ کی پروسیسنگ',
    'email_payment_refunded_content' => '                <br><br>
                ریفنڈ کی تفصیلات: <br>
                &bull; ٹرانزیکشن آئی ڈی: :id <br>
                &bull; ادائیگی کی تفصیلات: :description <br>
                &bull; ریفنڈ ہونے والی رقم: :amount_rounded :currency <br>
                &bull; ریفنڈ ہونے والا: :gateway_name <br><br>',
    'general' => 'جنرل',
    'renew' => 'تجدید کریں',
    'ptero_alerts_suspended' => 'یہ خدمت معطل ہو گئی ہے',
    'ptero_alerts_suspended_desc' => 'اس خدمت کے لئے یہ میعاد :due_date (:due_date_diff) تھا۔<br><br> ہم معاف کرتے ہیں کہ آپ کی خدمت کو برابر کرنے کے باعث آپ کی خدمت معطل ہو گئی ہے۔ ترمینیشن سے بچنے کے لئے براہ کرم ہے کہ چاہے جو بھی بقائی انوائسز کو :suspended_after دنوں کے اندر ادا کریں۔ اگر اس فریم ٹائم میں ادائیگی نہیں ہوئی تو آپ کی خدمت منسوخ ہوجائے گی، جس سے متعلقہ تمام ڈیٹا، فائلز، اور لائسنسز کا ڈیلیٹ یا ریووکیشن ہوجائے گا۔',
    'important' => 'اہم',
    'ptero_alerts_cancelled' => 'یہ خدمت منسوخ ہو گئی ہے',
    'ptero_alerts_cancelled_desc' => 'اس خدمت کو منسوخ کرنے کا آپ نے کر دیا ہے :cancelled_at (:cancelled_at_diff) تھا۔<br><br> اگر آپ نے اپنا فیصلہ بدل لیا ہے تو آپ اس تاریخ سے پہلے منسوخی کو واپس لے سکتے ہیں۔ اگر کوئی کارروائی نہیں کی گئی تو آپ کی خدمت معطل اور منسوخ ہوجائے گی۔ اس خدمت کے ساتھ جڑے تمام فائلز اور ڈیٹا ہمیشہ کے لئے ڈیلیٹ ہوجائے گے۔',
    'do_not_cancel' => 'منسوخ نہ کریں',
    'ptero_alerts_terminated' => 'یہ خدمت منسوخ ہوگئی ہے',
    'ptero_alerts_terminated_desc' => 'اس خدمت کو منسوخ کر دیا گیا ہے۔ منسوخی کا باعث ہو سکتا ہے کہ آپ ادائیگی میں دیر ہوگئی ہو یا آپ نے خدمت منسوخ کر لی ہو۔ اس خدمت کے ساتھ جڑے تمام ڈیٹا / فائلز / لائسنسز ڈیلیٹ یا ریووک کر دیے گئے ہیں۔ یہ پروسیس لازمی ہے۔',
    'ptero_alerts_failed_server' => 'آپ کے سرور بنانے میں ناکامی ہوگئی',
    'ptero_alerts_failed_server_desc' => 'ہم نے کوشش کی کہ آپ کے لئے ایک سرور بنائیں، مگر کچھ چیزیں ہمیشہ کے لئے غلط ہو گئیں۔ براہ کرم ایڈمنسٹریٹر سے رابطہ کریں تاکہ تفصیلی لاگز کو چیک کیا جا سکے۔',
    'login_to_panel' => 'پینل میں لاگ ان کریں',
    'cancel_plan' => 'پلان منسوخ کریں',
    'ptero_cancellation_fee_info' => '<span style="color:red;">اہم!</span> آپ کا پیکیج :cancellation_fee شامل ہے جو منسوخ کرنے کے لئے ادا کرنا ہوگا',
    'cancel_at_end_of_term' => 'مدت کے اختتام پر منسوخ کریں',
    'service_cancelled_gracefully_at_due_date' => 'آپ کی خدمت مدت کے اختتام پر اہمانی سے منسوخ ہوگی: :due_date',
    'cancel_immediately' => 'فوراً منسوخ کریں',
    'cancel_immediately_desc' => 'آپ کی خدمت 24 گھنٹوں میں منسوخ ہوگی۔ <br>آپ کی خدمت سے جڑے سبھی فائلز اور ڈیٹا فوراً ڈیلیٹ ہوجائے گا۔',
    'cancellation_reason' => 'منسوخی کا باعث',
    'payment_method_reason' => 'ادائیگی کا طریقہ کا باعث',
    'pay_with_balance' => 'بیلنس کے ساتھ ادائیگی',
    'discard' => 'رد کریں',
    'cancel_now' => 'ابھی منسوخ کریں',
    'ptero_server_options' => 'سرور کے اختیارات',
    'ptero_server_options_desc' => 'براہ کرم نیچے اپنی مرضی کے اختیارات منتخب کریں۔',
    'ptero_server_location' => 'سرور کا مقام',
    'ptero_renew_plan' => 'پلان تجدید کریں',
    'create_invoice' => 'انوائس بنائیں',
    'renew_for' => 'کے لئے تجدید کریں',
    'ptero_renew_desc' => 'آپ کی خدمت :due_date، :due_date_diff تک وقت ہوجاتی ہے۔<br><br>نیچے آپ اپنی خدمت کو اور :period کے لئے تجدید کر سکتے ہیں۔ "تجدید" پر کلک کرنے کے بعد، ہم آپ کے لئے ایک انوائس پیدا کریں گے جو آپ کو ادا کرنے کے لئے ہے۔',
    'create_location' => 'مقام بنائیں',
    'suspended' => 'معطل',
    'bill_to' => 'بل کیا گیا',
    'email_subscription_payment_completed_subject' => 'سبسکرپشن',
    'email_subscription_payment_content' => 'سبسکرپشن کو کامیابی سے ادا کر دیا گیا تھا',
    'account_suspended' => 'آپ کا اکاؤنٹ معطل ہوگیا ہے',
    'suspended_contact_for_information' => 'آپ کا اس ایپلیکیشن تک رسائی منسوخ ہو گئی ہے۔ اگر آپ یقین کرتے ہیں کہ یہ ایک غلطی تھی تو براہ کرم ہو کر ہم سے رابطہ کریں۔',
    'reference_id' => 'حوالہ ID: ',
    'apply' => 'لاگو کریں',
    'affiliate_discount_info' => '<span class="font-medium">افیلییٹ ڈسکاؤنٹ:</span> آپ کو ایک افیلییٹ نے دعوت دی ہے اور آپ کو <strong>:percent%</strong> ڈسکاؤنٹ مل رہا ہے!',
    'discount' => 'ڈسکاؤنٹ',
    'administrator' => 'ایڈمنسٹریٹر',
    'was_this_article_helpful' => 'کیا یہ مضمون مددگار تھا؟',
    'thank_you_your_feedback' => 'آپ کی رائے کا شکریہ',
    'discussion' => 'مباحثہ',
    'your_comment' => 'آپ کا تبادلہ',
    'post_comment' => 'تبادلہ پوسٹ کریں',
    'comment_settings' => 'تبادلہ کی ترتیبات',
    'report' => 'رپورٹ',
    'latest_news' => 'تازہ ترین خبریں',
    'latest_news_desc' => 'جمعیت میں ہونے والی باتوں اور نئی اپ ڈیٹس پر موصول ہوں۔',
    'read_more' => 'مزید پڑھیں',
    'news' => 'خبریں',
    'cookies_settings' => 'کوکی کی ترتیبات',

    'cookies_settings_description' => 'ان خدمات کا استعمال کرنے کے لئے، ہمیں آپکی رضا چاہیے ہوتی ہے۔ "سب کچھ قبول کریں" پر کلک کرکے، آپ تمام خدمات کا استعمال کرنے کی رضا دیتے ہیں۔ کوکیز اہم کاموں کے لئے استعمال ہوتی ہیں، جیسے کے آپکی سیشن کو جب آپ لاگ ان ہوتے ہیں، آپکو XSRF حملوں سے بچانا اور مزید۔',
    'essential_cookies' => 'ضروری کوکیز',
    'essential_cookies_description' => 'ان خدمات کا استعمال کرنے کے لئے، ہمیں آپکی رضا چاہیے ہوتی ہے۔ "سب کچھ قبول کریں" پر کلک کرکے، آپ تمام خدمات کا استعمال کرنے کی رضا دیتے ہیں۔ آپ ہر قسم کی کوکی کے لئے انفرادی طور پر سلائیڈرس پر کلک کرکے اور محفوظ کرکے بھی اپنی رضا دے سکتے ہیں۔',
    'functional_cookies' => 'فعالیت کوکیز',
    'functional_cookies_description' => 'ان خدمات کا استعمال کرنے کے لئے، ہمیں آپکی رضا چاہیے ہوتی ہے۔ "سب کچھ قبول کریں" پر کلک کرکے، آپ تمام خدمات کا استعمال کرنے کی رضا دیتے ہیں۔ آپ ہر قسم کی کوکی کے لئے انفرادی طور پر سلائیڈرس پر کلک کرکے اور محفوظ کرکے بھی اپنی رضا دے سکتے ہیں۔',
    'view_cookies' => 'کوکیز دیکھیں',
    'accept_all' => 'سب کچھ قبول کریں',
    'reject_all' => 'سب کچھ مسترد کریں',
    'download_my_data' => 'میرے ڈیٹا ڈاؤن لوڈ کریں',
    'download_data_description' => 'ہم آپکے ذخیرہ ہونے والے ڈیٹا کو جمع کرتے ہیں جو آپ ڈاؤن لوڈ کرنے کے وقت ہمارے پاس ہوتا ہے۔',
    'delete_my_account' => 'میرا اکاؤنٹ ڈیلیٹ کریں',
    'delete_account_description' => 'آپ ہم سے درخواست کر سکتے ہیں کہ ہم آپکا اکاؤنٹ ہماری پلیٹ فارم سے ڈیلیٹ کریں، یہ عمل غیر قابل واپسی ہے۔ یہ دائمی طور پر آپکا ذاتی ڈیٹا، ادائیگیاں اور لین دین کی تاریخ کو مٹا دیتا ہے، تمام آرڈرز کو منسوخ کر دیتا ہے، اور آپکی اکاؤنٹ بیلنس اور اکاؤنٹ سے متعلق کوئی اور ڈیٹا۔',
    'delete_account_disclosure' => 'میں سمجھتا ہوں کہ میرا اکاؤنٹ ڈائمیتلی ڈیلیٹ ہو جائے گا۔ میرے ڈیٹا کو جب ایک بار حذف کر دیا گیا ہے تو اسے واپس لانے کا کوئی طریقہ نہیں ہوتا، حتیٰ کہ ایڈمنسٹریٹر بھی نہ ہو۔',
    'delete_account' => 'اکاؤنٹ ڈیلیٹ کریں',
    'perm_account_deletion' => 'دائمی اکاؤنٹ ڈیلیٹ درخواست دی گئی ہے',
    'account_deleted_alert' => 'آپ کا اکاؤنٹ ہماری پلیٹ فارم سے دائمی طور پر ڈیلیٹ ہو جائے گا :time میں، "منسوخ" پر کلک کرکے اس درخواست کو واپس لینے کے لئے۔',
    'i_accept_the' => 'میں قبول کرتا ہوں',
    'terms_and_conditions' => 'شرائط و ضوابط',
    'explore_plans' => 'منصوبے کا تجزیہ کریں',
    'filter' => 'فلٹر',
    'filter_status' => 'فلٹر حالت',
    'false' => 'غلط',
    'true' => 'صحیح',
    'you_are_currently_logged_in_as_please_press_exit' => 'آپ حال ہی :username کے طور پر لاگ ان ہیں، براہ کرم <a href=":route" class="font-semibold underline hover:no-underline">باہر نکلنے</a> کے لئے دبائیں',
    'author' => 'مصنف',
    'write_a_comment' => 'تبادلہ لکھیں...',
    'name' => 'نام',
    'provider' => 'فراہم کنندہ',
    'expiration' => 'میعاد ختم ہونے کی تاریخ',
    'purpose' => 'مقصد',
    'cloudflare_inc' => 'کلاوڈفلیئر انکارپوریٹڈ',
    'year_1' => '1 سال',
    'static_file_delivery' => 'اسٹیٹک فائل ڈیلیوری',
    'session' => 'سیشن',
    'identifies_a_session_instance_for_a_user' => 'صارف کے لئے ایک سیشن مثال کو شناخت دیتا ہے',
    'prevent_crosssite_request_forgery_csrf_attacks' => 'کراس-سائٹ درخواست فورجری (CSRF) حملوں کو روکیں',
    'api_authentication' => 'API تصدیق',
    'toggle_me' => 'میری چھپائی ہوئی میں',
    'set_preffered_order_status' => 'پسندیدہ آرڈر حالت مرتب کریں',
    'order_must_be_active' => 'آپکی آرڈر حالت کو ایکٹو ہونی چاہئے تاکہ یہ عمل کر سکے',
    'collect_article_feedback' => 'مضمون کی تنقید جمع کریں',
    'affiliate' => 'افیلیئٹ',

    'track_users_invited_by_affiliates' => 'افیلیئٹس کے ذریعے دعوت یافتہ صارفوں کو ٹریک کریں',
    'keep_track_of_affiliate_invites' => 'افیلیئٹ چھوڑنے کا ٹریک رکھیں',
    'follow' => 'فالو',
    'following' => 'فالو کر رہا ہے',
    'followers' => 'پیروکار',
    'powered_by' => 'سے چلتا ہے',
    'company' => 'کمپنی',
    'marketplace' => 'مارکیٹ پلیس',
    'team' => 'ٹیم',
    'table_navigation' => 'ٹیبل کا نیویگیشن',
    'invoice_template' => 'انوائس ٹیمپلیٹ',
    'page' => 'صفحہ',
    'of' => 'کا',
    'invoice_date' => 'انوائس کی تاریخ',
    'invoice_no' => 'انوائس نمبر',
    'package_icon' => 'پیکیج آئیکن',
    'payment_info' => 'ادائیگی کی معلومات',
    'total_due' => 'کل واجب الادا',
    'transaction_id' => 'ٹرانزیکشن آئی ڈی',
    'payment_gateway' => 'ادائیگی گیٹ وے',
    'thank_you' => 'شکریہ!',
    'pay' => 'ادا کریں',
    'sidebar' => 'سائیڈ بار',
    'settings_page' => 'سیٹنگز پیج',
    'toggle_darkmode' => 'ڈارک موڈ ٹوگل کریں',
    'no_access_email_download' => 'آپ کو اس وسیلے تک رسائی نہیں ہے',
    'copied_successfully' => 'کامیابی کے ساتھ کاپی ہوگیا',
    'service_account' => ':service اکاؤنٹ',
    'change_password' => 'پاس ورڈ تبدیل کریں',
    'change_service_password' => 'اپنا :service پاس ورڈ تبدیل کریں',
    'cancel_subscription_to_continue' => 'آپ کو اس عمل کو کرنے کے لئے اپنے سبسکرپشن کو منسوخ کرنا ہوگا۔',
    'members' => 'ممبرز',
    'invites' => 'دعوتیں',
    'invited_by' => 'نے دعوت دی ہے',

    'member_invite_email_subject' => ':user نے آپ کو :service میں شامل ہونے کی دعوت دی ہے',
    'member_invite_email_content' => 'آپ کو :user نے :service میں شامل ہونے کی دعوت دی ہے۔ اپنی موجودہ دعوتیں دیکھنے اور انہیں منظم کرنے کے لئے نیچے دیے گئے بٹن پر کلک کریں۔',
    'member_invite_email_content_guest' => 'آپ کا ایمیل اس وقت ہمارے ساتھ رجسٹر نہیں ہے، براہ کرم اس ای میل سے رجسٹر کریں <strong>:email</strong>، رجسٹر ہونے کے بعد آپ نیچے دیے گئے بٹن پر کلک کر کے دعوت کو منظم کر سکتے ہیں۔',
    'view_invitation' => 'دعوت دیکھیں',
    'contact_us_success_subject' => 'آپکا رابطہ درخواست مل گئی ہے 🎉',
    'contact_us_success_content' => 'آپ ہم سے رابطہ کرنے کا شکریہ۔ ہم نے آپکی رابطہ درخواست حاصل کی ہے جس کا عنوان ہے: ":subject"۔ ہماری ٹیم ہر ممکنہ زودی آپ تک واپسی پہنچنے کی کوشش کرے گی۔',
    'personal_details' => 'شخصی تفصیلات',
    'personal_details_desc' => 'براہ کرم اپنی شخصی تفصیلات درج کریں',
    'custom_options' => 'اپنی پسندیدہ اختیارات',
    'custom_options_desc' => 'اپنے پیکیج کے لئے اپنے خدمات کے اختیارات کو تخصیص دیں',
    'games' => 'کھیلوں',

];
