<?php

return [

    'accepted' => ' :attribute قبول ہونا ضروری ہے',
    'active_url' => ' :attribute ایک درست URL نہیں ہے',
    'after' => ' :attribute کی تاریخ :date کے بعد ہونی چاہئے',
    'after_or_equal' => ' :attribute کی تاریخ :date کے بعد یا اس کے برابر ہونی چاہئے',
    'alpha' => ' :attribute میں صرف حروف ہو سکتے ہیں',
    'alpha_dash' => ' :attribute میں صرف حروف، اعداد، اور ڈیشز ہو سکتے ہیں',
    'alpha_num' => ' :attribute میں صرف حروف اور اعداد ہو سکتے ہیں',
    'array' => ' :attribute ایک ایرے ہونا ضروری ہے',
    'before' => ' :attribute کی تاریخ :date کے پہلے ہونی چاہئے',
    'before_or_equal' => ' :attribute کی تاریخ :date کے پہلے یا اس کے برابر ہونی چاہئے',
    'between' => [
        'numeric' => ' :attribute کی قیمت :min اور :max کے درمیان ہونی چاہئے',
        'file' => ' :attribute کا سائز :min اور :max کلوبائٹس کے درمیان ہونا چاہئے',
        'string' => ' :attribute کی لمبائی :min اور :max حروف کے درمیان ہونی چاہئے',
        'array' => ' :attribute میں :min اور :max آئٹمز ہونی چاہئے',
    ],

    'boolean' => ' :attribute فیلڈ ٹھیک یا غلط ہونا ضروری ہے',
    'confirmed' => ' :attribute کی تصدیق میل نہیں ہو رہی',
    'date' => ' :attribute ایک درست تاریخ نہیں ہے',
    'date_format' => ' :attribute کی شکل :format سے میل نہیں ہو رہی',
    'different' => ' :attribute اور :other مختلف ہونے چاہئے',
    'digits' => ' :attribute کو :digits ہنر ہونے چاہئے',
    'digits_between' => ' :attribute کی لمبائی :min اور :max ہنر کے درمیان ہونی چاہئے',
    'dimensions' => ' :attribute کی غلط تصویر کی وسیعت ہے',
    'distinct' => ' :attribute فیلڈ میں ایک ہی قیمت ہونی چاہئے',
    'email' => ' :attribute ایک درست ای میل پتہ ہونا ضروری ہے',
    'exists' => ' منتخب کردہ :attribute غلط ہے',
    'file' => ' :attribute ایک فائل ہونی چاہئے',
    'filled' => ' :attribute فیلڈ ضروری ہے',
    'image' => ' :attribute ایک تصویر ہونی چاہئے',
    'in' => ' منتخب کردہ :attribute غلط ہے',
    'in_array' => ' :attribute فیلڈ :other میں موجود نہیں ہے',
    'integer' => ' :attribute صحیح عدد ہونا چاہئے',
    'ip' => ' :attribute ایک درست IP پتہ ہونا ضروری ہے',
    'json' => ' :attribute ایک درست JSON ہونا ضروری ہے',
    'max' => [
        'numeric' => ' :attribute کی قیمت :max سے زیادہ نہیں ہو سکتی',
        'file' => ' :attribute کا سائز :max کلوبائٹس سے زیادہ نہیں ہو سکتا',
        'string' => ' :attribute کی لمبائی :max حروف سے زیادہ نہیں ہو سکتی',
        'array' => ' :attribute میں :max آئٹمز سے زیادہ نہیں ہو سکتے',
    ],

    'mimes' => ' :attribute کی قسم :values ہونی چاہئے',
    'mimetypes' => ' :attribute کی قسم :values ہونی چاہئے',
    'min' => [
        'numeric' => ' :attribute کم سے کم :min ہونا چاہئے',
        'file' => ' :attribute کا سائز کم سے کم :min کلوبائٹس ہونا چاہئے',
        'string' => ' :attribute کی لمبائی کم سے کم :min حروف ہونی چاہئے',
        'array' => ' :attribute میں کم سے کم :min آئٹمز ہونے چاہئے',
    ],
    'not_in' => ' منتخب کردہ :attribute غلط ہے',
    'numeric' => ' :attribute ایک عدد ہونا چاہئے',
    'present' => ' :attribute فیلڈ موجود ہونا چاہئے',
    'regex' => ' :attribute کی فارمیٹ غلط ہے',
    'required' => ' :attribute فیلڈ ضروری ہے',
    'required_if' => ' :other :value ہونے پر :attribute فیلڈ ضروری ہے',
    'required_unless' => ' :values میں نہ ہونے پر :attribute فیلڈ ضروری ہے',
    'required_with' => ' :values موجود ہونے پر :attribute فیلڈ ضروری ہے',
    'required_with_all' => ' :values موجود ہونے پر :attribute فیلڈ ضروری ہے',
    'required_without' => ' :values نہ ہونے پر :attribute فیلڈ ضروری ہے',
    'required_without_all' => ' :values میں کوئی بھی نہ ہونے پر :attribute فیلڈ ضروری ہے',
    'same' => ' :attribute اور :other میں میل ہونا چاہئے',
    'size' => [
        'numeric' => ' :attribute کا سائز :size ہونا چاہئے',
        'file' => ' :attribute کا سائز :size کلوبائٹس ہونا چاہئے',
        'string' => ' :attribute کی لمبائی :size حروف ہونی چاہئے',
        'array' => ' :attribute میں :size آئٹمز ہونے چاہئے',
    ],
    'string' => ' :attribute ایک سٹرنگ ہونا چاہئے',
    'timezone' => ' :attribute ایک درست ٹائم زون ہونا چاہئے',
    'unique' => ' :attribute پہلے ہی لیا گیا ہے',
    'uploaded' => ' :attribute اپ لوڈ کرنے میں ناکام رہا',
    'url' => ' :attribute کی فارمیٹ غلط ہے',

    'attributes' => [],
];
