<?php

return [
    'choose_domain' => 'Elige un dominio...',
    'reg_new_domain' => 'Registrar nuevo dominio',
    'use_own_domain' => 'Usar tu propio dominio',
    'description' => 'Descripción',
    'balance_before_transaction' => 'Saldo antes de la transacción',
    'amount' => 'Cantidad',
    'date' => 'Fecha',
    'your_services' => 'Tus Servicios',
    'results' => 'resultados',
    'more_info' => 'Más información',
    'showing' => 'Mostrando :count de :all resultados',
    'add_balance' => 'Agregar Saldo',
    'order_new_service' => 'Ordenar nuevo servicio',
    'terminated' => 'Terminado',
    'cancelled' => 'Cancelado',
    'expand_collapse_row' => 'Expandir/Contraer Fila',
    'product' => 'Producto',
    'service' => 'Servicio',
    'category' => 'Categoría',
    'status' => 'Estado',
    'details' => 'Detalles',
    'package' => 'Paquete',
    'billing_cycle' => 'Ciclo de facturación',
    'due_date' => 'Fecha de vencimiento',
    'last_renewal_date' => 'Última fecha de renovación',
    'next_invoice' => 'Próxima Factura',
    'no_orders_found' => 'No se encontraron órdenes',
    'no_orders_found_desc' => 'Todavía no has realizado ninguna orden, las nuevas órdenes se mostrarán aquí.',
    'paid' => 'Pagado',
    'unpaid' => 'Impago',
    'refunded' => 'Reembolsado',
    'actions' => 'Acciones',
    'no_records_found' => 'No se encontraron registros',
    'no_record_found_desc' => 'Aún no has :paid ninguna factura, las facturas :paid aparecerán aquí.',
    'invoice' => 'Factura',
    'payment_not_received' => 'El pago aún no ha sido recibido.',
    'checking_in' => 'Registrando',
    'bitpave_payment_engine' => 'Potenciado por el motor de pago de Bitpave',
    'payment_details' => 'Detalles del Pago',
    'payment_total_is' => 'El total de tu pago es de $:is para :for',
    'bitpave_instruction' => '1. Abre tu aplicación de billetera de Bitcoin o escanea el código QR<br>
                    2. Envía <u>exactamente</u> <strong>:price</strong> BTC a
                    <strong>:wallet</strong><br>
                    3. ¡Listo! 🚀 🙌',
    'wallet' => 'Billetera',
    'bitcoin_amount' => 'Cantidad de Bitcoin',
    'awaiting_payment' => 'Esperando pago...',
    'session_expired' => 'Sesión expirada',
    'copied' => 'Copiado',
    'scanning_payments' => 'Escaneando pagos',
    'stripe_card_payment' => 'Pago con tarjeta de crédito o débito',
    'credit_debit_card' => 'Tarjeta de crédito o débito',
    'submit_payment' => 'Enviar pago',
    'provide_missing_information' => 'Proporcionar información faltante',
    'provide_missing_information_desc' => 'Es necesario recopilar información como la dirección. Completa el siguiente formulario para continuar.',
    'optional' => '(opcional)',
    'organization' => 'Organización',
    'company_name' => 'Nombre de la empresa',
    'select_an_option' => 'Seleccionar una opción',
    'address' => 'Dirección',
    'city' => 'Ciudad',
    'zip_code' => 'Código postal',
    'state_region_provice' => 'Estado / Región / Provincia',
    'region' => 'Región',
    'save_all' => 'Guardar todo',
    'info' => 'Información',
    'unpaid_warn' => 'Tienes <span class="font-medium">:count</span> factura(s) pendiente(s) de pago. Páguelas a tiempo para evitar interrupciones en tu(s) servicio(s).',
    'services' => 'Servicios',
    'invoices' => 'Facturas',
    'balance' => 'Saldo',
    'change_color' => 'Cambiar color',
    'customize_your_preference' => 'Personaliza según tus preferencias',
    'rose' => 'rosa',
    'pink' => 'rosado',
    'fuchsia' => 'fucsia',
    'purple' => 'morado',
    'violet' => 'violeta',
    'indigo' => 'índigo',
    'blue' => 'azul',
    'sky' => 'cielo',
    'cyan' => 'cian',
    'teal' => 'verde azulado',
    'emerald' => 'esmeralda',
    'green' => 'verde',
    'lime' => 'lima',
    'yellow' => 'amarillo',
    'amber' => 'ámbar',
    'orange' => 'naranja',
    'red' => 'rojo',
    'stone' => 'piedra',
    'neutral' => 'neutral',
    'zinc' => 'cinc',
    'gray' => 'gris',
    'slate' => 'pizarra',
    'login' => 'Iniciar sesión',
    'view_notifications' => 'Ver notificaciones',
    'notifications' => 'Notificaciones',
    'icon_description' => 'Descripción del icono',
    'mark_as_read' => 'Marcar como leído',
    'email_history' => 'Historial de correo electrónico',
    'invoice_history' => 'Historial de facturas',
    'apps' => 'Aplicaciones',
    'open_user_menu' => 'Abrir menú de usuario',
    'account_settings' => 'Configuración de la cuenta',
    'online' => 'En línea',
    'away' => 'Ausente',
    'busy' => 'Ocupado',
    'appear_offline' => 'Aparecer desconectado',
    'subscriptions' => 'Suscripciones',
    'admin' => 'Administrador',
    'sign_out' => 'Cerrar sesión',
    'last_login_at' => 'Último inicio de sesión en',
    'never' => 'Nunca',
    'member_since' => 'Miembro desde',
    'visibility' => 'Visibilidad',
    'update' => 'Actualizar',
    'dashboard' => 'Panel de control',
    'store' => 'Tienda',
    'view_all' => 'Ver todo',
    'maintenance_mode_enabled' => 'Modo de mantenimiento habilitado',
    'maintenance_mode_desc' => 'Actualmente, este panel no está accesible para los clientes porque se ha habilitado el modo de mantenimiento. Actualmente estás pasando por alto el modo de mantenimiento.',
    'disable_maintenance' => 'Desactivar mantenimiento',
    'dismiss' => 'Descartar',
    'view_all_services' => 'Ver todos los servicios',
    'close_menu' => 'Cerrar menú',
    'balance_sidebar_desc' => 'Una vez que se complete el pago, el monto que hayas seleccionado se acreditará en tu saldo de cuenta, lo que te permitirá renovar tus servicios o realizar nuevos pedidos.',
    'balance_how_add' => '¿Cuánto quieres agregar?',
    'pay_now' => 'Pagar ahora',
    'help_center' => 'Centro de ayuda',
    'resources' => 'Recursos',
    'legal' => 'Legal',
    'all_rights_reserved' => 'Todos los derechos reservados.',
    'price_block_desc' => 'Primero :period :symbol:total_price luego :symbol:renewal_price por :per_period',
    'enter_domain' => 'Ingresar dominio',
    'enter_domain_desc' => 'Por favor, ingresa el dominio donde deseas usar este servicio.',
    'domain' => 'Dominio',
    'enter_domain_helper' => 'Por favor, ingresa el dominio exacto. Ejemplo: example.com o si estás usando un subdominio web.example.com',
    'payment_method' => 'Método de pago',
    'payment_method_desc' => 'Selecciona el método de pago deseado',
    'subscription' => 'Suscripción',
    'custom_notes' => 'Notas personalizadas',
    'custom_notes_desc' => 'Puedes incluir cualquier solicitud especial o cosas que debamos saber.',
    'custom_notes_placeholder' => 'Escribe tus pensamientos aquí...',
    'order_summary' => 'Resumen del pedido',
    'recurring' => 'Recurrente',
    'due_today' => 'Vencimiento hoy',
    'complete_checkout' => 'Completar pago',
    'selected_price_includes_cancellation_fee' => '*El ciclo de precio seleccionado incluye una tarifa de cancelación de',
    'setup_fee' => 'Tarifa de configuración',
    'payment_canceled' => 'Pago cancelado',
    'payment_canceled_desc' => 'Tu pago ha sido cancelado, por favor inténtalo de nuevo.',
    'back_dashboard' => 'Volver al panel de control',
    'view_invoice' => 'Ver factura',
    'pricing' => 'Precios',
    'pricing_for' => 'Precios para',
    'get_started' => 'Empezar',
    'payment_successfully' => 'Pago realizado con éxito',
    'payment_successfully_desc' => 'Gracias por completar el pago, estamos preparando todo para ti.',
    'create_subscription' => 'Crear suscripción',
    'subscription_name' => 'Nombre de la suscripción',
    'order' => 'Pedido',
    'gateway' => 'Pasarela',
    'billed_as' => 'Facturado como',
    'next_billing_date' => 'Fecha de próxima facturación',
    'created_at' => 'Creado el',
    'active' => 'Activo',
    'days' => 'días',
    'manage' => 'Administrar',
    'cancel' => 'Cancelar',
    'close_modal' => 'Cerrar modal',
    'subscription_order_desc' => 'Puedes crear una suscripción para pedidos existentes para pagar automáticamente cuando sea necesario.',
    'subscription_order' => 'Pedido de suscripción',
    'subscription_price' => 'Precio de suscripción',
    'create' => 'Crear',
    'cancelling' => 'Cancelando',
    'managing' => 'Gestionando',
    'close' => 'Cerrar',
    'profile' => 'Perfil',
    'client' => 'Cliente',
    'drag_and_drop' => '<span class="font-semibold">Haz clic para subir</span> o arrastra y suelta',
    'upload' => 'Subir',
    'two_factor_authentication' => 'Autenticación de dos factores',
    'two_factor_authentication_desc' => 'La autenticación de dos factores agrega una capa adicional de seguridad a tu cuenta al requerir algo más que una contraseña para iniciar sesión.',
    'social_accounts' => 'Cuentas sociales',
    'google_account' => 'Cuenta de Google',
    'not_connected' => 'No conectado',
    'remove' => 'Eliminar',
    'connect' => 'Conectar',
    'github_account' => 'Cuenta de GitHub',
    'discord_account' => 'Cuenta de Discord',
    'enable' => 'Habilitar',
    'disable' => 'Deshabilitar',
    'download' => 'Descargar',
    'sessions' => 'Sesiones',
    'last_seen' => 'Última vez visto',
    'revoked' => 'Revocado',
    'revoke' => 'Revocar',
    'general_information' => 'Información general',
    'username' => 'Nombre de usuario',
    'email' => 'Email',
    'first_name' => 'Nombre',
    'subscribe_to_emails' => 'Suscribirse a correos electrónicos',
    'contact_us' => 'Contáctanos',
    'contact_us_desc' => '¿Quieres informar de un error o necesitas ayuda para encontrar el producto adecuado? Haremos todo lo posible para responderte.',
    'subject' => 'Asunto',
    'subject_contact_us_placeholder' => 'Cuéntanos cómo podemos ayudarte',
    'your_message' => 'Tu mensaje',
    'send_message' => 'Enviar mensaje',
    'email_history_desc' => 'Explora todos los correos electrónicos enviados a tu cuenta',
    'sender' => 'Remitente',
    'address_only_vissible' => 'La dirección solo es visible para',
    'item' => 'Artículo',
    'price' => 'Precio',
    'qty' => 'Cantidad',
    'discounts' => 'Descuentos',
    'total' => 'Total',
    'subtotal' => 'Subtotal',
    'tax_rate' => 'Tasa de impuesto',
    'complete_payment' => 'Completar pago',
    'share' => 'Compartir',
    'sownload' => 'Descargar',
    'share_invoice_desc' => 'Puedes compartir esta factura con otro usuario para que la pague con su pasarela de pago. Los detalles de tu dirección o nombre completo no se compartirán en la factura.',
    'last_updated' => 'Última actualización',
    'hello' => 'Hola',
    'email_template_content' => 'Si tienes alguna pregunta adicional o necesitas asistencia continua, no dudes en contactarnos a través de nuestro portal en línea. Nuestro equipo dedicado está disponible para ayudarte de manera rápida y eficiente a través del sistema de tickets.',
    'regards' => 'Saludos',
    'email_button_desc' => 'Si tienes problemas al hacer clic en el botón ":button", copia y pega la siguiente URL en tu navegador web:',
    'open_main_menu' => 'Abrir menú principal',
    'home' => 'Inicio',
    'features' => 'Características',
    'contact' => 'Contacto',
    'portal_redirect' => 'Redirección del portal',
    'portal_redirect_url' => 'URL de redirección del portal',
    'portal_header_image' => 'Imagen de encabezado del portal',
    'default_category' => 'Categoría predeterminada',
    'submit' => 'Enviar',
    'host_favorite_games' => 'Hospedamos tus juegos favoritos',
    'rust' => 'Rust',
    'minecraft' => 'Minecraft',
    'ack' => 'ARK: SE',
    'our_game_anel' => 'Nuestro panel de juegos',
    'our_game_anel_desc' => 'Aquí en :app nos enfocamos en mercados donde la tecnología, la innovación y el capital pueden desbloquear valor a largo plazo y promover el crecimiento económico.',
    'file_manager' => 'Administrador de archivos',
    'file_manager_desc' => 'Nuestro administrador de archivos te permite cargar, crear, descargar, establecer permisos, comprimir y descomprimir archivos y administrarlos de manera sencilla',
    'plugins_manager' => 'Administrador de plugins',
    'plugins_manager_desc' => 'Elige entre más de 60000 plugins e instálalos con solo un clic',
    'backup_manager' => 'Administrador de copias de seguridad',
    'backup_manager_desc' => 'Nuestro panel te permite realizar copias de seguridad de tus archivos en cualquier momento',
    'user_manager' => 'Administrador de usuarios',
    'user_manager_desc' => 'Invita a amigos o miembros del personal a tu panel. Puedes establecer ciertos permisos por miembro',
    'schedule_manager' => 'Administrador de programación',
    'schedule_manager_desc' => 'Nuestro sistema de programación te permite establecer controles de energía programados, copias de seguridad o tareas',
    'database_manager' => 'Administrador de bases de datos',
    'database_manager_desc' => 'Genera bases de datos MySQL, crea nuevas asignaciones y mucho más',
    'viewing_plans_for' => 'Viendo planes para',
    'no_plans_display' => 'No hay planes para mostrar',
    'no_plans_display_desc' => 'No has creado ningún plan para mostrar en el portal, por favor crea planes para empezar',
    'other_categories' => 'Otras categorías',
    'selected' => 'Seleccionado',
    'get_started_now' => 'Empezar ahora',
    'register_your_account_no-time' => '¡Registra tu cuenta y pon tu servidor en marcha en poco tiempo!',
    'create_my_account' => 'Crear mi cuenta',
    'try_again' => 'Inténtalo de nuevo',
    'please_login_to_view' => 'Por favor, inicia sesión para ver esta página.',
    'page_not_published' => 'La página aún no se ha publicado.',
    'email_new_device_subject' => 'Un nuevo dispositivo ha iniciado sesión en tu cuenta de :app_name',
    'email_check_activity_btn' => 'Ver actividad',
    'email_add_device_content' => '
                <br><br>
                Detalles del dispositivo: <br>
                &bull; Dispositivo: :device_name <br>
                &bull; Tipo de dispositivo: :device_type <br>
                &bull; Dirección IP: :ip_address <br>
                &bull; Último inicio de sesión en: :last_login_at <br>
                &bull; Agente de usuario: <code>:user_agent</code> <br><br>

                Si no fuiste tú, revoca el acceso inmediatamente a este dispositivo y contáctanos.',
    'manage_service' => 'Administrar Servicio',
    'email_cancel_order_subject' => 'Tu servicio ha sido cancelado',
    'email_cancel_order_content' => '
            <br><br>
            Detalles del Servicio: <br>
            &bull; ID: #:id <br>
            &bull; Nombre del Servicio: :name <br>
            &bull; Período de gracia hasta: :period <br>
            &bull; Motivo de cancelación: <code>:reason</code> <br><br>',
    'email_payment_completed_subject' => 'Pago realizado',
    'email_payment_completed_button' => 'Ver factura',
    'email_payment_completed_content' => '                <br><br>
                Detalles del pago: <br>
                &bull; ID de la transacción: :id <br>
                &bull; Descripción del pago: :description <br>
                &bull; Monto del pago: :amount_rounded :currency <br>
                &bull; Método de pago: :gateway_name <br><br>

                Ten la seguridad de que tu pago se ha aplicado a tu cuenta y todas las facturas relevantes o saldos pendientes se han actualizado en consecuencia. <br>',
    'email_payment_refunded_subject' => 'Reembolso en proceso',
    'email_payment_refunded_content' => '                <br><br>
                Detalles del reembolso: <br>
                &bull; ID de la transacción: :id <br>
                &bull; Descripción del pago: :description <br>
                &bull; Monto reembolsado: :amount_rounded :currency <br>
                &bull; Reembolsado a: :gateway_name <br><br>',
    'general' => 'General',
    'renew' => 'Renovar',
    'ptero_alerts_suspended' => 'Este servicio ha sido suspendido',
    'ptero_alerts_suspended_desc' => 'La fecha de vencimiento de este servicio fue el :due_date (:due_date_diff)<br><br> Lamentamos informarte que tu servicio ha sido suspendido debido a un pago vencido. Para evitar la terminación, por favor liquida cualquier factura pendiente dentro de :suspended_after días desde la fecha de vencimiento. Si el pago no se recibe dentro de este plazo, tu servicio será terminado, lo que resultará en la eliminación o revocación de todos los datos, archivos y licencias asociadas.',
    'important' => 'Importante',
    'ptero_alerts_cancelled' => 'Este servicio ha sido cancelado',
    'ptero_alerts_cancelled_desc' => 'Este servicio está programado para ser cancelado el :cancelled_at (:cancelled_at_diff)<br><br> Si has cambiado de opinión, puedes deshacer la cancelación antes de esta fecha. Si no se toma ninguna acción, tu servicio será suspendido y terminado. Todos los archivos y datos pertenecientes a este servicio se eliminarán para siempre.',
    'do_not_cancel' => 'No Cancelar',
    'ptero_alerts_terminated' => 'Este servicio ha sido terminado',
    'ptero_alerts_terminated_desc' => 'Este servicio fue terminado. La terminación puede ocurrir debido a varias razones. No pagaste a tiempo o cancelaste el servicio. Todos los datos / archivos / licencias pertenecientes a este servicio han sido eliminados o revocados. Este proceso es irreversible',
    'ptero_alerts_failed_server' => 'No se pudo generar tu servidor',
    'ptero_alerts_failed_server_desc' => 'Intentamos crear un servidor para ti, sin embargo, algo salió mal. Por favor, contacta a un administrador para revisar el pedido desde el área de administración para obtener registros más detallados.',
    'login_to_panel' => 'Iniciar sesión en el Panel',
    'cancel_plan' => 'Cancelar Plan',
    'ptero_cancellation_fee_info' => '¡Importante!</span> Tu paquete incluye una tarifa de cancelación de :symbol:cancellation_fee que debe pagarse para cancelar',
    'cancel_at_end_of_term' => 'Cancelar al final del periodo',
    'service_cancelled_gracefully_at_due_date' => 'Tu servicio se cancelará de forma elegante en la fecha de vencimiento: :due_date',
    'cancel_immediately' => 'Cancelar inmediatamente',
    'cancel_immediately_desc' => 'Tu servicio se cancelará en un plazo de 24 horas. <br>Todos los archivos y datos adjuntos a tu servicio se eliminarán de inmediato.</p>',
    'cancellation_reason' => 'Motivo de cancelación',
    'payment_method_reason' => 'Motivo de método de pago',
    'pay_with_balance' => 'Pagar con Saldo',
    'discard' => 'Descartar',
    'cancel_now' => 'Cancelar Ahora',
    'ptero_server_options' => 'Opciones del Servidor',
    'ptero_server_options_desc' => 'Por favor, selecciona tus opciones deseadas a continuación.',
    'ptero_server_location' => 'Ubicación del Servidor',
    'ptero_renew_plan' => 'Renovar Plan',
    'create_invoice' => 'Crear Factura',
    'renew_for' => 'Renovar por',
    'ptero_renew_desc' => 'Tu servicio expira el :due_date, :due_date_diff.<br><br>A continuación, puedes renovar tu servicio por otros :period. Después de hacer clic en "Renovar", generaremos una factura para que la pagues.',
    'create_location' => 'Crear Ubicación',
];
