<?php

return [
    'choose_domain' => 'Escolha um domínio...',
    'reg_new_domain' => 'Registrar novo domínio',
    'use_own_domain' => 'Usar seu próprio domínio',
    'description' => 'Descrição',
    'balance_before_transaction' => 'Saldo antes da transação',
    'amount' => 'Valor',
    'date' => 'Data',
    'your_services' => 'Seus Serviços',
    'results' => 'resultados',
    'more_info' => 'Mais informações',
    'showing' => 'Mostrando :count de :all resultados',
    'add_balance' => 'Adicionar Saldo',
    'order_new_service' => 'Encomendar novo serviço',
    'terminated' => 'Encerrado',
    'cancelled' => 'Cancelado',
    'expand_collapse_row' => 'Expandir/Recolher Linha',
    'product' => 'Produto',
    'service' => 'Serviço',
    'category' => 'Categoria',
    'status' => 'Status',
    'details' => 'Detalhes',
    'package' => 'Pacote',
    'billing_cycle' => 'Ciclo de Faturamento',
    'due_date' => 'Data de Vencimento',
    'last_renewal_date' => 'Última data de renovação',
    'next_invoice' => 'Próxima Fatura',
    'no_orders_found' => 'Nenhum pedido encontrado',
    'no_orders_found_desc' => 'Você ainda não fez nenhum pedido, novos pedidos serão visíveis aqui.',
    'paid' => 'Pago',
    'unpaid' => 'Não Pago',
    'refunded' => 'Reembolsado',
    'actions' => 'Ações',
    'no_records_found' => 'Nenhum registro encontrado',
    'no_record_found_desc' => 'Você ainda não pagou nenhuma fatura, faturas pagas aparecerão aqui',
    'invoice' => 'Fatura',
    'payment_not_received' => 'Pagamento ainda não recebido.',
    'checking_in' => 'Verificando',
    'bitpave_payment_engine' => 'Powered by Bitpave payment engine',
    'payment_details' => 'Detalhes do Pagamento',
    'payment_total_is' => 'O total do seu pagamento é $:is para :for',
    'bitpave_instruction' => '1. Abra o seu aplicativo de Carteira de Bitcoins ou Escaneie o código QR<br>
                        2. Envie <u>exatamente</u> <strong>:price</strong> BTC para
                        <strong>:wallet</strong><br>
                        3. Você está pronto 🚀 🙌',
    'wallet' => 'Carteira',
    'bitcoin_amount' => 'Quantidade de Bitcoins',
    'awaiting_payment' => 'Aguardando pagamento...',
    'session_expired' => 'Sessão Expirada',
    'copied' => 'Copiado',
    'scanning_payments' => 'Escaneando pagamentos',
    'stripe_card_payment' => 'Pagamento com Cartão',
    'credit_debit_card' => 'Cartão de crédito ou débito',
    'submit_payment' => 'Enviar Pagamento',
    'provide_missing_information' => 'Fornecer informações faltantes',
    'provide_missing_information_desc' => 'Precisamos coletar informações como o Endereço. Por favor, complete o formulário abaixo para continuar.',
    'optional' => '(opcional)',
    'organization' => 'Organização',
    'company_name' => 'Nome da Empresa',
    'select_an_option' => 'Selecionar uma opção',
    'address' => 'endereço',
    'city' => 'Cidade',
    'zip_code' => 'Código Postal',
    'state_region_provice' => 'Estado / Região / Província',
    'region' => 'Região',
    'save_all' => 'Salvar tudo',
    'info' => 'Informação',
    'unpaid_warn' => 'Você possui <span class="font-medium">:count</span> fatura(s) não pagas. Pague-as a tempo para evitar qualquer interrupção no(s) seu(s) serviço(s).',
    'services' => 'Serviços',
    'invoices' => 'Faturas',
    'balance' => 'Saldo',
    'change_color' => 'Mudar cor',
    'customize_your_preference' => 'Personalize de acordo com sua preferência',
    'rose' => 'rosa',
    'pink' => 'rosa',
    'fuchsia' => 'fúcsia',
    'purple' => 'roxo',
    'violet' => 'violeta',
    'indigo' => 'índigo',
    'blue' => 'azul',
    'sky' => 'azul céu',
    'cyan' => 'ciano',
    'teal' => 'verde-azulado',
    'emerald' => 'esmeralda',
    'green' => 'verde',
    'lime' => 'verde-limão',
    'yellow' => 'amarelo',
    'amber' => 'âmbar',
    'orange' => 'laranja',
    'red' => 'vermelho',
    'stone' => 'pedra',
    'neutral' => 'neutro',
    'zinc' => 'zinco',
    'gray' => 'cinza',
    'slate' => 'ardósia',
    'login' => 'Entrar',
    'view_notifications' => 'Ver notificações',
    'notifications' => 'Notificações',
    'icon_description' => 'Descrição do ícone',
    'mark_as_read' => 'Marcar como lido',
    'email_history' => 'Histórico de e-mails',
    'invoice_history' => 'Histórico de faturas',
    'apps' => 'Aplicativos',
    'open_user_menu' => 'Abrir menu do usuário',
    'account_settings' => 'Configurações da conta',
    'online' => 'Online',
    'away' => 'Ausente',
    'busy' => 'Ocupado',
    'appear_offline' => 'Aparecer offline',
    'subscriptions' => 'Assinaturas',
    'admin' => 'Admin',
    'sign_out' => 'Sair',
    'last_login_at' => 'Último login em',
    'never' => 'Nunca',
    'member_since' => 'Membro desde',
    'visibility' => 'Visibilidade',
    'update' => 'Atualizar',
    'dashboard' => 'Painel',
    'store' => 'Loja',
    'view_all' => 'Ver todos',
    'maintenance_mode_enabled' => 'Modo de manutenção ativado',
    'maintenance_mode_desc' => 'Este painel está atualmente inacessível para clientes, pois o modo de manutenção está ativado. Você está atualmente ignorando o modo de manutenção.',
    'disable_maintenance' => 'Desativar Manutenção',
    'dismiss' => 'Fechar',
    'view_all_services' => 'Ver todos os serviços',
    'close_menu' => 'Fechar menu',
    'balance_sidebar_desc' => 'Assim que o pagamento for concluído, o valor que você selecionou será creditado no saldo da sua conta, permitindo que você renove seus serviços ou faça novos pedidos.',
    'balance_how_add' => 'Quanto você deseja adicionar?',
    'pay_now' => 'Pagar agora',
    'help_center' => 'Central de Ajuda',
    'resources' => 'Recursos',
    'legal' => 'Legal',
    'all_rights_reserved' => 'Todos os direitos reservados.',
    'price_block_desc' => 'Primeiro :period :symbol:total_price depois :symbol:renewal_price por :per_period',
    'enter_domain' => 'Digite o domínio',
    'enter_domain_desc' => 'Digite o domínio onde você deseja usar este serviço.',
    'domain' => 'Domínio',
    'enter_domain_helper' => 'Por favor, digite o domínio exato. Exemplo: exemplo.com ou, se estiver usando um subdomínio, web.exemplo.com<',
    'payment_method' => 'Método de pagamento',
    'payment_method_desc' => 'Selecione o método de pagamento desejado',
    'subscription' => 'Assinatura',
    'custom_notes' => 'Notas personalizadas',
    'custom_notes_desc' => 'Você pode incluir solicitações especiais ou informações que precisamos saber.',
    'custom_notes_placeholder' => 'Escreva suas observações aqui...',
    'order_summary' => 'Resumo do pedido',
    'recurring' => 'Recorrente',
    'due_today' => 'Vencimento hoje',
    'complete_checkout' => 'Finalizar compra',
    'selected_price_includes_cancellation_fee' => '*O ciclo de preço selecionado inclui uma taxa de cancelamento de',
    'setup_fee' => 'Taxa de configuração',
    'payment_canceled' => 'Pagamento cancelado',
    'payment_canceled_desc' => 'Seu pagamento foi cancelado. Por favor, tente novamente.',
    'back_dashboard' => 'Voltar para o Painel',
    'view_invoice' => 'Ver fatura',
    'pricing' => 'Preços',
    'pricing_for_service' => 'Preços para :service',
    'get_started' => 'Começar',        
    'payment_successfully' => 'Pagamento realizado com sucesso',
    'payment_successfully_desc' => 'Obrigado por concluir o pagamento, estamos preparando tudo para você.',
    'create_subscription' => 'Criar Assinatura',
    'subscription_name' => 'Nome da Assinatura',
    'order' => 'Pedido',
    'gateway' => 'Gateway',
    'billed_as' => 'Faturado como',
    'next_billing_date' => 'Próxima Data de Cobrança',
    'created_at' => 'Criado em',
    'active' => 'Ativo',
    'days' => 'dias',
    'manage' => 'Gerenciar',
    'cancel' => 'Cancelar',
    'close_modal' => 'Fechar modal',
    'subscription_order_desc' => 'Você pode criar uma assinatura para pedidos existentes para pagá-los automaticamente na hora certa.',
    'subscription_order' => 'Pedido de Assinatura',
    'subscription_price' => 'Preço da Assinatura',
    'create' => 'Criar',
    'cancelling' => 'Cancelando',
    'managing' => 'Gerenciando',
    'close' => 'Fechar',
    'profile' => 'Perfil',
    'client' => 'Cliente',
    'drag_and_drop' => '<span class="font-semibold">Clique para fazer o upload</span> ou arraste e solte',
    'upload' => 'Enviar',
    'two_factor_authentication' => 'Autenticação de Dois Fatores',
    'two_factor_authentication_desc' => 'A autenticação de dois fatores adiciona uma camada adicional de segurança à sua conta, exigindo mais do que apenas uma senha para fazer login.',
    'social_accounts' => 'Contas sociais',
    'google_account' => 'Conta do Google',
    'not_connected' => 'Não conectado',
    'remove' => 'Remover',
    'connect' => 'Conectar',
    'github_account' => 'Conta do Github',
    'discord_account' => 'Conta do Discord',
    'enable' => 'Ativar',
    'disable' => 'Desativar',
    'download' => 'Baixar',
    'sessions' => 'Sessões',
    'last_seen' => 'Última visualização',
    'revoked' => 'Revogada',
    'revoke' => 'Revogar',
    'general_information' => 'Informações gerais',
    'username' => 'Nome de usuário',
    'email' => 'E-mail',
    'first_name' => 'Primeiro Nome',
    'subscribe_to_emails' => 'Inscrever-se para receber e-mails',
    'contact_us' => 'Contate-nos',
    'contact_us_desc' => 'Quer relatar um bug ou precisa de ajuda para encontrar o produto certo? Faremos o nosso melhor para responder a você.',
    'subject' => 'Assunto',
    'subject_contact_us_placeholder' => 'Informe como podemos ajudar você',
    'your_message' => 'Sua mensagem',
    'send_message' => 'Enviar mensagem',
    'email_history_desc' => 'Navegue por todos os e-mails enviados para a sua conta',
    'sender' => 'Remetente',
    'address_only_vissible' => 'O endereço é visível apenas para',
    'item' => 'Item',
    'price' => 'Preço',
    'qty' => 'Quantidade',
    'discounts' => 'Descontos',
    'total' => 'Total',
    'subtotal' => 'Subtotal',
    'tax_rate' => 'Taxa de imposto',
    'complete_payment' => 'Concluir Pagamento',
    'share' => 'Compartilhar',
    'download' => 'Baixar',
    'share_invoice_desc' => 'Você pode compartilhar esta fatura com outro usuário para que eles possam pagá-la com o gateway de pagamento deles. Seus detalhes de endereço ou nome completo não serão compartilhados na fatura.',
    'last_updated' => 'Última Atualização',
    'hello' => 'Olá',
    'email_template_content' => 'Caso você tenha mais perguntas ou precise de suporte contínuo, sinta-se à vontade para entrar em contato conosco por meio do nosso portal online. Nossa equipe dedicada está disponível para ajudá-lo prontamente e de forma eficiente por meio do sistema de tickets.',
    'regards' => 'Atenciosamente',
    'email_button_desc' => 'Se você estiver com dificuldades para clicar no botão ":button", copie e cole o URL abaixo em seu navegador da web:',
    'open_main_menu' => 'Abrir menu principal',
    'home' => 'Início',
    'features' => 'Recursos',
    'contact' => 'Contato',
    'portal_redirect' => 'Redirecionamento do Portal',
    'portal_redirect_url' => 'URL de Redirecionamento do Portal',
    'portal_header_image' => 'Imagem de Cabeçalho do Portal',
    'default_category' => 'Categoria Padrão',
    'submit' => 'Enviar',
    'host_favorite_games' => 'Hospedamos seus jogos favoritos',
    'rust' => 'Rust',
    'minecraft' => 'Minecraft',
    'ack' => 'ARK: SE',
    'our_game_panel' => 'Nosso Painel de Jogos',
    'our_game_panel_desc' => 'Aqui no :app, focamos em mercados onde a tecnologia, inovação e capital podem desbloquear valor a longo prazo e impulsionar o crescimento econômico.',
    'file_manager' => 'Gerenciador de Arquivos',
    'file_manager_desc' => 'Nosso gerenciador de arquivos permite que você faça upload, crie, baixe, defina permissões, compacte e descompacte arquivos e os gerencie de maneira fácil',
    'plugins_manager' => 'Gerenciador de Plugins',
    'plugins_manager_desc' => 'Escolha entre mais de 60.000 plugins e instale com apenas um clique',
    'backup_manager' => 'Gerenciador de Backups',
    'backup_manager_desc' => 'Nosso painel permite que você faça backups de seus arquivos a qualquer momento',
    'user_manager' => 'Gerenciador de Usuários',
    'user_manager_desc' => 'Convide amigos ou membros da equipe para o seu painel. Você pode definir permissões específicas por membro',
    'schedule_manager' => 'Gerenciador de Tarefas Agendadas',
    'schedule_manager_desc' => 'Nosso sistema de tarefas agendadas permite que você defina controles de energia temporizados, backups ou tarefas',
    'database_manager' => 'Gerenciador de Banco de Dados',
    'database_manager_desc' => 'Gerenciar Bancos de Dados MySQL, crie novas alocações e muito mais',
    'viewing_plans_for' => 'Visualizando planos para',
    'no_plans_display' => 'Nenhum plano para exibir',
    'no_plans_display_desc' => 'Você ainda não criou nenhum plano para exibir no portal, por favor, crie planos para começar',
    'other_categories' => 'Outras Categorias',
    'selected' => 'Selecionado',
    'get_started_now' => 'Comece Agora',
    'register_your_account_no-time' => 'Registre sua conta e coloque seu servidor em funcionamento em pouco tempo!',
    'create_my_account' => 'Criar minha conta',
    'try_again' => 'Tentar Novamente',
    'please_login_to_view' => 'Por favor, faça login para visualizar esta página.',
    'page_not_published' => 'A página ainda não foi publicada.',
    'email_new_device_subject' => 'Um novo dispositivo fez login na sua conta :app_name',
    'email_check_activity_btn' => 'Verificar atividade',
    'email_add_device_content' => '
                    <br><br>
                    Detalhes do Dispositivo: <br>
                    &bull; Dispositivo: :device_name <br>
                    &bull; Tipo de Dispositivo: :device_type <br>
                    &bull; Endereço IP: :ip_address <br>
                    &bull; Último Login em: :last_login_at <br>
                    &bull; Agente do Usuário: <code>:user_agent</code> <br><br>
    
                    Se isso não foi você, revogue imediatamente o acesso a este dispositivo e altere sua senha.',
    'manage_service' => 'Gerenciar Serviço',
    'email_cancel_order_subject' => 'Seu serviço foi cancelado',
    'email_cancel_order_content' => '
                <br><br>
                Detalhes do Serviço: <br>
                &bull; ID: #:id <br>
                &bull; Nome do Serviço: :name <br>
                &bull; Período de Carência até: :period <br>
                &bull; Motivo do Cancelamento: <code>:reason</code> <br><br>',
    'email_payment_completed_subject' => 'Pagamento Realizado',
    'email_payment_completed_button' => 'Ver fatura',
    'email_payment_completed_content' => '                <br><br>
                    Detalhes do Pagamento: <br>
                    &bull; ID da Transação: :id <br>
                    &bull; Descrição do Pagamento: :description <br>
                    &bull; Valor do Pagamento: :amount_rounded :currency <br>
                    &bull; Método de Pagamento: :gateway_name <br><br>
    
                    Tenha certeza de que seu pagamento foi aplicado à sua conta e quaisquer faturas relevantes ou saldos pendentes foram atualizados de acordo.<br>',
    'email_payment_refunded_subject' => 'Processando Reembolso',
    'email_payment_refunded_content' => '                <br><br>
                    Detalhes do Reembolso: <br>
                    &bull; ID da Transação: :id <br>
                    &bull; Descrição do Pagamento: :description <br>
                    &bull; Valor Reembolsado: :amount_rounded :currency <br>
                    &bull; Reembolsado para: :gateway_name <br><br>',
    'general' => 'Geral',
    'renew' => 'Renovar',
    'ptero_alerts_suspended' => 'Este serviço foi suspenso',
    'ptero_alerts_suspended_desc' => 'A data de vencimento para este serviço era em :due_date (:due_date_diff)<br><br> Lamentamos informar que seu serviço foi suspenso devido a pagamentos em atraso. Para evitar o término, por favor, liquide quaisquer faturas pendentes dentro de :suspended_after dias a partir da data de vencimento. Caso o pagamento não seja recebido dentro deste prazo, o serviço será encerrado, resultando na exclusão ou revogação de todos os dados, arquivos e licenças associados.',
    'important' => 'Importante',
    'ptero_alerts_cancelled' => 'Este serviço foi cancelado',
    'ptero_alerts_cancelled_desc' => 'Este serviço está configurado para ser cancelado em :cancelled_at (:cancelled_at_diff)<br><br> Se você mudou de ideia, você pode desfazer o cancelamento antes desta data. Se nenhuma ação for tomada, o serviço será suspenso e encerrado. Todos os arquivos e dados pertencentes a este serviço serão excluídos permanentemente.',
    'do_not_cancel' => 'Não Cancelar',
    'ptero_alerts_terminated' => 'Este serviço foi encerrado',
    'ptero_alerts_terminated_desc' => 'Este serviço foi encerrado. O encerramento pode ocorrer por diversos motivos. Você atrasou o pagamento ou cancelou o serviço. Todos os dados / arquivos / licenças pertencentes a este serviço foram excluídos ou revogados. Este processo é irreversível.',
    'ptero_alerts_failed_server' => 'Falha ao criar o seu servidor',
    'ptero_alerts_failed_server_desc' => 'Nós tentamos criar um servidor para você, no entanto, algo deu errado. Por favor, entre em contato com um Administrador para verificar o pedido na área de administração para obter mais detalhes.',
    'login_to_panel' => 'Acesse o Painel',
    'cancel_plan' => 'Cancelar Plano',
    'ptero_cancellation_fee_info' => 'Importante! Seu pacote inclui uma taxa de cancelamento de :symbol:cancellation_fee que deve ser paga para cancelar',
    'cancel_at_end_of_term' => 'Cancelar no final do período',
    'service_cancelled_gracefully_at_due_date' => 'Seu serviço será cancelado de forma adequada na data de vencimento: :due_date',
    'cancel_immediately' => 'Cancelar imediatamente',
    'cancel_immediately_desc' => 'Seu serviço será cancelado dentro de 24 horas. <br>Todos os arquivos e dados associados ao seu serviço serão excluídos imediatamente.</p>',
    'cancellation_reason' => 'Motivo do Cancelamento',
    'payment_method_reason' => 'Motivo do Método de Pagamento',
    'pay_with_balance' => 'Pagar com Saldo',
    'discard' => 'Descartar',
    'cancel_now' => 'Cancelar Agora',
    'ptero_server_options' => 'Opções do Servidor',
    'ptero_server_options_desc' => 'Por favor, selecione as opções desejadas abaixo.',
    'ptero_server_location' => 'Localização do Servidor',
    'ptero_renew_plan' => 'Renovar Plano',
    'create_invoice' => 'Criar Fatura',
    'renew_for' => 'Renovar por',
    'ptero_renew_desc' => 'Seu serviço expira em :due_date, :due_date_diff.<br><br>Abaixo você pode renovar seu serviço por mais :period. Após clicar em "Renovar", geraremos uma fatura para que você possa pagar.',
    'create_location' => 'Criar Localização',
    
];
