<?php

return [
    'choose_domain' => 'ドメインを選択...',
    'reg_new_domain' => '新しいドメインを登録する',
    'use_own_domain' => '独自ドメインを使用する',
    'description' => '説明',
    'balance_before_transaction' => '取引前残高',
    'amount' => '量',
    'date' => '日付',
    'your_services' => 'あなたのサービス',
    'results' => '結果',
    'more_info' => 'もっと情報',
    'showing' => ':count の :all 結果を表示',
    'add_balance' => '残高を追加する',
    'order_new_service' => '新しいサービスを注文する',
    'terminated' => '終了',
    'cancelled' => 'キャンセル',
    'expand_collapse_row' => '行を展開/折りたたむ',
    'product' => '製品',
    'service' => 'サービス',
    'category' => 'カテゴリ',
    'status' => 'ステータス',
    'details' => '詳細',
    'package' => 'パッケージ',
    'billing_cycle' => '課金サイクル',
    'due_date' => '期日',
    'last_renewal_date' => '最終更新日',
    'next_invoice' => '次回請求書',
    'no_orders_found' => '注文が見つかりません',
    'no_orders_found_desc' => 'まだ注文は行っていないため、ここに新しい注文が表示されます。',
    'paid' => '支払済み',
    'unpaid' => '未払い',
    'refunded' => '払い戻し済み',
    'actions' => 'アクション',
    'no_records_found' => 'レコードが見つかりません',
    'no_record_found_desc' => ':paid の請求書はまだありません。ここに表示されます。',
    'invoice' => '請求書',
    'payment_not_received' => '支払いがまだ受領されていません。',
    'checking_in' => 'チェックイン中',
    'bitpave_payment_engine' => 'Bitpave 決済エンジンで提供',
    'payment_details' => '支払い詳細',
    'payment_total_is' => 'お支払い合計は $:is で、:for です。',
    'bitpave_instruction' => '1. ビットコインウォレットアプリを開くか、QRコードをスキャンしてください。<br>
                    2. <strong>正確に</strong> <strong>:price</strong> BTC を <strong>:wallet</strong> に送金してください。<br>
                    3. 完了です 🚀 🙌',
    'wallet' => 'ウォレット',
    'bitcoin_amount' => 'ビットコイン量',
    'awaiting_payment' => '支払い待ち...',
    'session_expired' => 'セッションが期限切れです',
    'copied' => 'コピー済み',
    'scanning_payments' => '支払いをスキャン中',
    'stripe_card_payment' => 'Stripe カード決済',
    'credit_debit_card' => 'クレジットカードまたはデビットカード',
    'submit_payment' => '支払いを提出する',
    'provide_missing_information' => '不足している情報の提供',
    'provide_missing_information_desc' => '住所などの情報を収集する必要がある場合があります。 続行するには、以下のフォームに記入してください。',
    'optional' => '(任意)',
    'organization' => '組織',
    'company_name' => '会社名',
    'select_an_option' => 'オプションを選択',
    'address' => '住所',
    'city' => '市',
    'zip_code' => '郵便番号',
    'state_region_provice' => '州 / 地域 / 県',
    'region' => '地域',
    'save_all' => 'すべて保存',
    'info' => '情報',
    'unpaid_warn' => '未払いの請求書が <span class="font-medium">:count</span> 件あります。サービスの中断を避けるために、時間内に支払ってください。',
    'services' => 'サービス',
    'invoices' => '請求書',
    'balance' => '残高',
    'change_color' => '色を変更',
    'customize_your_preference' => '好みに合わせてカスタマイズ',
    'rose' => 'ローズ',
    'pink' => 'ピンク',
    'fuchsia' => 'フクシア',
    'purple' => '紫',
    'violet' => 'バイオレット',
    'indigo' => 'インディゴ',
    'blue' => '青',
    'sky' => 'スカイ',
    'cyan' => 'シアン',
    'teal' => 'ティール',
    'emerald' => 'エメラルド',
    'green' => '緑',
    'lime' => 'ライム',
    'yellow' => '黄色',
    'amber' => 'アンバー',
    'orange' => 'オレンジ',
    'red' => '赤',
    'stone' => 'ストーン',
    'neutral' => 'ニュートラル',
    'zinc' => '亜鉛',
    'gray' => '灰色',
    'slate' => 'スレート',
    'login' => 'ログイン',
    'view_notifications' => '通知を表示',
    'notifications' => '通知',
    'icon_description' => 'アイコンの説明',
    'mark_as_read' => '既読にする',
    'email_history' => 'メール履歴',
    'invoice_history' => '請求書履歴',
    'apps' => 'アプリ',
    'open_user_menu' => 'ユーザーメニューを開く',
    'account_settings' => 'アカウント設定',
    'online' => 'オンライン',
    'away' => '離れて',
    'busy' => '忙しい',
    'appear_offline' => 'オフラインに見える',
    'subscriptions' => 'サブスクリプション',
    'admin' => '管理者',
    'sign_out' => 'サインアウト',
    'last_login_at' => '最終ログイン日時',
    'never' => '決して',
    'member_since' => '加入日',
    'visibility' => '表示設定',
    'update' => '更新',
    'dashboard' => 'ダッシュボード',
    'store' => 'ストア',
    'view_all' => 'すべて表示',
    'maintenance_mode_enabled' => 'メンテナンスモードが有効になっています',
    'maintenance_mode_desc' => '現在、メンテナンスモードが有効になっているため、クライアントはこのパネルにアクセスできません。あなたは現在、メンテナンスモードをバイパスしています。',
    'disable_maintenance' => 'メンテナンスを無効にする',
    'dismiss' => '閉じる',
    'view_all_services' => 'すべてのサービスを表示',
    'close_menu' => 'メニューを閉じる',
    'balance_sidebar_desc' => '支払いが完了すると、選択した金額がアカウント残高にクレジットされ、サービスを更新したり新しい注文をしたりできるようになります。',
    'balance_how_add' => 'いくら追加しますか？',
    'pay_now' => '今すぐ支払う',
    'help_center' => 'ヘルプセンター',
    'resources' => 'リソース',
    'legal' => '法的事項',
    'all_rights_reserved' => '全著作権所有。',
    'price_block_desc' => '最初の :period :total_price、その後 :renewal_price 毎に :per_period',
    'enter_domain' => 'ドメインを入力',
    'enter_domain_desc' => 'このサービスを使用するドメインを入力してください。',
    'domain' => 'ドメイン',
    'enter_domain_helper' => '正確なドメインを入力してください。例: example.com、またはサブドメインを使用している場合は web.example.com<',
    'payment_method' => '支払い方法',
    'payment_method_desc' => '希望の支払い方法を選択してください',
    'subscription' => 'サブスクリプション',
    'custom_notes' => 'カスタムノート',
    'custom_notes_desc' => '特別なリクエストや知っておくべきことを含めることができます。',
    'custom_notes_placeholder' => 'ここに考えを書いてください...',
    'order_summary' => '注文の要約',
    'recurring' => '定期的',
    'due_today' => '今日の支払い',
    'complete_checkout' => 'チェックアウトを完了する',
    'selected_price_includes_cancellation_fee' => '*選択した価格にはキャンセル料が含まれています',
    'setup_fee' => 'セットアップ料',
    'payment_canceled' => '支払いがキャンセルされました',
    'payment_canceled_desc' => '支払いがキャンセルされました。もう一度お試しください。',
    'back_dashboard' => 'ダッシュボードに戻る',
    'view_invoice' => '請求書を表示',
    'pricing' => '価格',
    'pricing_for_service' => '価格 :service',
    'get_started' => '始める',
    'payment_successfully' => '支払いが成功しました',
    'payment_successfully_desc' => '支払いが正常に完了しました。すべての準備が整っています。',
    'create_subscription' => 'サブスクリプションを作成',
    'subscription_name' => 'サブスクリプション名',
    'order' => '注文',
    'gateway' => 'ゲートウェイ',
    'billed_as' => 'として請求',
    'next_billing_date' => '次回請求日',
    'created_at' => '作成日時',
    'active' => 'アクティブ',
    'days' => '日',
    'manage' => '管理',
    'cancel' => 'キャンセル',
    'close_modal' => 'モーダルを閉じる',
    'subscription_order_desc' => '既存の注文のサブスクリプションを作成して、支払い時に自動的に支払うことができます。',
    'subscription_order' => 'サブスクリプション注文',
    'subscription_price' => 'サブスクリプション価格',
    'create' => '作成',
    'cancelling' => 'キャンセル中',
    'managing' => '管理中',
    'close' => '閉じる',
    'profile' => 'プロフィール',
    'client' => 'クライアント',
    'drag_and_drop' => '<span class="font-semibold">クリックしてアップロード</span> またはドラッグアンドドロップ',
    'upload' => 'アップロード',
    'two_factor_authentication' => '二要素認証',
    'two_factor_authentication_desc' => '二要素認証は、パスワードだけでなく、追加のセキュリティ層を提供するためにアカウントに必要なものです。',
    'social_accounts' => 'ソーシャルアカウント',
    'google_account' => 'Googleアカウント',
    'not_connected' => '接続されていません',
    'remove' => '削除',
    'connect' => '接続',
    'github_account' => 'Githubアカウント',
    'discord_account' => 'Discordアカウント',
    'enable' => '有効にする',
    'disable' => '無効にする',
    'download' => 'ダウンロード',
    'sessions' => 'セッション',
    'last_seen' => '最後に見た日時',
    'revoked' => '取り消し',
    'revoke' => '取り消す',
    'general_information' => '一般情報',
    'username' => 'ユーザー名',
    'email' => 'メール',
    'first_name' => '名前',
    'subscribe_to_emails' => 'メール購読',
    'contact_us' => 'お問い合わせ',
    'contact_us_desc' => 'バグを報告したり、適切な製品を見つけるのに助けが必要ですか？できる限り返信いたします。',
    'subject' => '件名',
    'subject_contact_us_placeholder' => 'どのようにお手伝いできますか？',
    'your_message' => 'メッセージ',
    'send_message' => 'メッセージを送信',
    'email_history_desc' => 'アカウントに送信されたすべてのメールを閲覧できます',
    'sender' => '送信者',
    'address_only_vissible' => '住所は以下にのみ表示されます',
    'item' => 'アイテム',
    'price' => '価格',
    'qty' => '数量',
    'discounts' => '割引',
    'total' => '合計',
    'subtotal' => '小計',
    'tax_rate' => '税率',
    'complete_payment' => '支払い完了',
    'share' => '共有',
    'sownload' => 'ダウンロード',
    'share_invoice_desc' => 'この請求書を他のユーザーと共有して、彼らに支払いゲートウェイで支払わせることができます。請求書には住所詳細やフルネームは表示されません。',
    'last_updated' => '最終更新日',
    'hello' => 'こんにちは',
    'email_template_content' => 'さらなるお問い合わせや継続的なサポートが必要な場合は、オンラインポータルを通じてお気軽にお問い合わせください。専門のチームがチケットシステムを介して迅速かつ効率的にお手伝いいたします。',
    'regards' => 'よろしく',
    'email_button_desc' => '":button" ボタンをクリックできない場合、以下のURLをWebブラウザにコピーして貼り付けてください:',
    'open_main_menu' => 'メインメニューを開く',
    'home' => 'ホーム',
    'features' => '特徴',
    'contact' => 'お問い合わせ',
    'portal_redirect' => 'ポータルリダイレクト',
    'portal_redirect_url' => 'ポータルリダイレクトURL',
    'portal_header_image' => 'ポータルヘッダー画像',
    'default_category' => 'デフォルトカテゴリ',
    'submit' => '送信',
    'host_favorite_games' => 'お気に入りのゲームをホストします',
    'rust' => 'Rust',
    'minecraft' => 'Minecraft',
    'ack' => 'ARK: SE',
    'our_game_anel' => '私たちのゲームパネル',
    'our_game_anel_desc' => 'ここでは、技術、イノベーション、資本が長期的な価値を開放し、経済成長を推進できる市場に焦点を当てています。',
    'file_manager' => 'ファイルマネージャ',
    'file_manager_desc' => 'ファイルマネージャを使用して、ファイルをアップロード、作成、ダウンロード、アクセス許可の設定、ファイルの圧縮および解凍、簡単な方法で管理できます。',
    'plugins_manager' => 'プラグインマネージャ',
    'plugins_manager_desc' => '60,000以上のプラグインから選択し、ボタンをクリックするだけでインストールできます。',
    'backup_manager' => 'バックアップマネージャ',
    'backup_manager_desc' => 'ダッシュボードを使用して、いつでもファイルのバックアップを取得できます。',
    'user_manager' => 'ユーザーマネージャ',
    'user_manager_desc' => '友達やスタッフメンバーをダッシュボードに招待します。メンバーごとに特定の権限を設定できます。',
    'schedule_manager' => 'スケジュールマネージャ',
    'schedule_manager_desc' => 'スケジュールシステムを使用して、タイミングの制御、バックアップ、タスクの設定を行うことができます。',
    'database_manager' => 'データベースマネージャ',
    'database_manager_desc' => 'MySQLデータベースを生成し、新しい割り当てなどを作成できます。',
    'viewing_plans_for' => '表示中のプラン',
    'no_plans_display' => '表示するプランがありません',
    'no_plans_display_desc' => 'ポータルに表示するプランを作成していないため、プランが表示されません。始めるにはプランを作成してください。',
    'other_categories' => 'その他のカテゴリ',
    'selected' => '選択済み',
    'get_started_now' => '今すぐ始める',
    'register_your_account_no-time' => 'アカウントを登録してサーバーをすぐに起動させましょう！',
    'create_my_account' => 'アカウントを作成',
    'try_again' => 'もう一度試す',
    'please_login_to_view' => 'このページを表示するにはログインしてください。',
    'page_not_published' => 'ページはまだ公開されていません。',
    'email_new_device_subject' => ':app_name アカウントに新しいデバイスがログインしました',
    'email_check_activity_btn' => 'アクティビティを確認',
    'email_add_device_content' => '
                <br><br>
                デバイスの詳細: <br>
                &bull; デバイス: :device_name <br>
                &bull; デバイスタイプ: :device_type <br>
                &bull; IPアドレス: :ip_address <br>
                &bull; 最終ログイン日時: :last_login_at <br>
                &bull; ユーザーエージェント: <code>:user_agent</code> <br><br>

                もし自分がログインしていない場合は、すぐにこのデバイスへのアクセスを取り消し、お問い合わせください。',
    'manage_service' => 'サービスを管理',
    'email_cancel_order_subject' => 'サービスがキャンセルされました',
    'email_cancel_order_content' => '
            <br><br>
            サービスの詳細: <br>
            &bull; ID: #:id <br>
            &bull; サービス名: :name <br>
            &bull; グレース期間終了日: :period <br>
            &bull; キャンセル理由: <code>:reason</code> <br><br>',
    'email_payment_completed_subject' => '支払い完了',
    'email_payment_completed_button' => '請求書を表示',
    'email_payment_completed_content' => '                <br><br>
                支払いの詳細: <br>
                &bull; トランザクションID: :id <br>
                &bull; 支払い説明: :description <br>
                &bull; 支払い金額: :amount_rounded :currency <br>
                &bull; 支払い方法: :gateway_name <br><br>

                お支払いは正常にアカウントに適用され、関連する請求書または未払いの残高が適切に更新されました。 <br>',
    'email_payment_refunded_subject' => '払い戻し処理中',
    'email_payment_refunded_content' => '                <br><br>
                払い戻しの詳細: <br>
                &bull; トランザクションID: :id <br>
                &bull; 払い戻し説明: :description <br>
                &bull; 払い戻し額: :amount_rounded :currency <br>
                &bull; 払い戻し先: :gateway_name <br><br>',
    'general' => '一般',
    'renew' => '更新',
    'ptero_alerts_suspended' => 'このサービスは一時停止されました',
    'ptero_alerts_suspended_desc' => 'このサービスの期限は :due_date (:due_date_diff) でした。<br><br>未払いのため、お客様のサービスが一時停止されました。終了を回避するために、期限切れから :suspended_after 日以内に未払いの請求書を支払ってください。この期間内に支払いがない場合、サービスは終了し、関連するすべてのデータ、ファイル、ライセンスが削除または取り消しになります。',
    'important' => '重要',
    'ptero_alerts_cancelled' => 'このサービスはキャンセルされました',
    'ptero_alerts_cancelled_desc' => 'このサービスは :cancelled_at (:cancelled_at_diff) にキャンセルされるように設定されています。<br><br>キャンセルを取り消すことができます。キャンセルを取り消さない場合、サービスは一時停止され、終了します。このサービスに関連するすべてのファイルとデータは永遠に削除されます。',
    'do_not_cancel' => 'キャンセルしない',
    'ptero_alerts_terminated' => 'このサービスは終了しました',
    'ptero_alerts_terminated_desc' => 'このサービスは終了しました。終了はいくつかの理由で発生する可能性があります。支払いが遅れたか、サービスをキャンセルしたかです。このサービスに関連するすべてのデータ/ファイル/ライセンスが削除または取り消されました。このプロセスは不可逆的です。',
    'ptero_alerts_failed_server' => 'サーバーの生成に失敗しました',
    'ptero_alerts_failed_server_desc' => 'サーバーの作成を試みましたが、何か問題が発生しました。詳細なログを確認するために、管理者からの注文をチェックするには、管理エリアからお問い合わせください。',
    'login_to_panel' => 'パネルにログイン',
    'cancel_plan' => 'プランをキャンセル',
    'ptero_cancellation_fee_info' => '重要！</span> パッケージにはキャンセル手数料が含まれており、キャンセルするために支払う必要があります :symbol:cancellation_fee',
    'cancel_at_end_of_term' => '期限切れ時にキャンセル',
    'service_cancelled_gracefully_at_due_date' => 'サービスは期限切れ時に優雅にキャンセルされます： :due_date',
    'cancel_immediately' => '即時キャンセル',
    'cancel_immediately_desc' => 'サービスは24時間以内にキャンセルされます。<br>サービスに添付されているすべてのファイルとデータは即座に削除されます。</p>',
    'cancellation_reason' => 'キャンセル理由',
    'payment_method_reason' => '支払い方法の理由',
    'pay_with_balance' => '残高で支払う',
    'discard' => '破棄',
    'cancel_now' => '今すぐキャンセル',
    'ptero_server_options' => 'サーバーオプション',
    'ptero_server_options_desc' => '以下から希望するオプションを選択してください。',
    'ptero_server_location' => 'サーバーの場所',
    'ptero_renew_plan' => 'プランを更新',
    'create_invoice' => '請求書を作成',
    'renew_for' => '次のために更新',
    'ptero_renew_desc' => 'サービスの有効期限は :due_date、:due_date_diff で切れます。<br><br>以下から :period 分のサービスを更新できます。 "更新" をクリックすると、請求書が生成され、支払うための請求書が生成されます。',
    'create_location' => '場所を作成',
    'suspended' => '一時停止',
    'bill_to' => '請求先',
    'email_subscription_payment_completed_subject' => '購読',
    'email_subscription_payment_content' => '購読が正常に支払われました',
    'account_suspended' => 'アカウントが一時停止されました',
    'suspended_contact_for_information' => 'このアプリケーションへのアクセスが取り消されました。これが誤りだと思われる場合は、お問い合わせください。',
    'reference_id' => '参照ID：',
    'apply' => '適用する',
    'affiliate_discount_info' => '<span class="font-medium">アフィリエイト割引:</span> アフィリエイトから招待され、<strong>:percent%</strong> の割引を受けています！',
    'discount' => '割引',
    'administrator' => '管理者',
    'was_this_article_helpful' => 'この記事は役に立ちましたか？',
    'thank_you_your_feedback' => 'フィードバックありがとうございます',
    'discussion' => 'ディスカッション',
    'your_comment' => 'あなたのコメント',
    'post_comment' => 'コメントを投稿',
    'comment_settings' => 'コメント設定',
    'report' => '報告',
    'latest_news' => '最新ニュース',
    'latest_news_desc' => 'コミュニティで何が起こっているかや新しいアップデートについて最新情報を入手してください。',
    'read_more' => '詳細を読む',
    'news' => 'ニュース',
];
