<?php

return [
    'accepted' => 'The :attributeが受け入れられなければなりません。',
    'active_url' => 'The :attributeは無効なURLです。',
    'after' => 'The :attributeは、:dateの後の日付でなければなりません。',
    'after_or_equal' => ': attributeは、: date以降の日付でなければなりません。',
    'alpha' => 'The :attribute には文字のみを含めることができます。',
    'alpha_dash' => 'The :attribute には、文字、数字、およびダッシュのみを含めることができます。',
    'alpha_num' => 'The :attribute には、文字と数字のみを含むことができます。',
    'array' => 'The :attribute は配列でなければなりません。',
    'before' => 'The :attribute は、:dateの前の日付でなければなりません。',
    'before_or_equal' => ': attributeは: date以前の日付である必要があります。',
    'between' => [
        'numeric' => 'The :attributeは:min 桁と:max桁の間でなければなりません。',
        'file' => 'The :属性の間でなければなりません: 分と: キロバイトの最大します。',
        'string' => 'The :属性の間でなければなりません: 分と: 文字の最大します。',
        'array' => 'The :間属性する必要があります: 分、: アイテムの最大します。',
    ],
    'boolean' => 'The :attributeフィールドは、真理値でなければなりません。',
    'confirmed' => 'The :attribute確認が一致しません。',
    'date' => 'The :attributeは無効なURLです。',
    'date_format' => 'The :attributeは:formatの形式と一致しません。',
    'different' => 'The :attributeと :other は異なっていなければなりません。',
    'digits' => 'The :attributeは:digits 桁の数字でなければなりません。',
    'digits_between' => 'The :attributeは:min 桁と:max桁の間でなければなりません。',
    'dimensions' => ':attributeに無効なサイズのイメージがあります。',
    'distinct' => ':attributeフィールドの値が重複しています。',
    'email' => 'The :attributeは、有効なメールアドレスでなければなりません。',
    'exists' => '選択された:attributeは無効です。',
    'file' => ':attributeはファイルでなければなりません。',
    'filled' => 'The :attributeフィールドが必要です。',
    'image' => 'The :attribute must be an image.',
    'in' => '選択された:attributeは無効です。',
    'in_array' => ':otherに:attributeフィールドは存在しません。',
    'integer' => 'The :attributeは整数でなければなりません。',
    'ip' => 'The :attributeは、有効なメールアドレスでなければなりません。',
    'json' => ':attributeは有効なJSON文字列でなければなりません。',
    'max' => [
        'numeric' => 'The :属性はより大きいかもしれない: 最大。',
        'file' => 'The :属性はより大きいかもしれない: キロバイトの最大します。',
        'string' => 'The :属性はより大きいかもしれない: 文字の最大します。',
        'array' => 'The :属性がない可能性があります以上: 最高のアイテム。',
    ],
    'mimes' => 'The :attributeは: :valuesタイプのファイルでなければなりません。',
    'mimetypes' => 'The :attributeは: :valuesタイプのファイルでなければなりません。',
    'min' => [
        'numeric' => 'The :属性が少なくともする必要があります: 分。',
        'file' => 'The :属性が少なくともする必要があります: 最小キロバイト。',
        'string' => 'The :属性が少なくともする必要があります: 文字分。',
        'array' => 'The :属性を少なくともいる必要があります: 分アイテム。',
    ],
    'not_in' => '選択された:attributeは無効です。',
    'numeric' => 'The :attribute は数値でなければなりません。',
    'present' => ':attribute フィールドが存在しなければなりません。',
    'regex' => 'The :attribute の形式が無効です。',
    'required' => 'The :attributeフィールドが必要です。',
    'required_if' => 'The :attribute フィールドはother が :valueのときにはが必要です 。',
    'required_unless' => ':otherが :valuesでない限り、:attributeフィールドが必要です。',
    'required_with' => 'The :attribute フィールドがvaluesが存在しているときには必要です。',
    'required_with_all' => 'The :attribute フィールドがvaluesが存在しているときには必要です。',
    'required_without' => 'The :attribute フィールド存在している時にはがvaluesが必要です。',
    'required_without_all' => 'The :attribute フィールドが存在しないときにはvaluesが必要です。',
    'same' => 'The :attribute and :other must match.',
    'size' => [
        'numeric' => 'The :attributeで: サイズが必要です。',
        'file' => 'The :attributeがキロバイトのサイズが必要です。',
        'string' => 'The :attribute の文字のサイズの必要です。',
        'array' => 'The :attribute: 項目のサイズを含める必要があります',
    ],
    'string' => ':attributeは文字列でなければなりません。',
    'timezone' => 'The :attribute は有効なゾーンでなければなりません。',
    'unique' => 'The :attribute はすでに使用されています。',
    'uploaded' => ':attributeは、アップロードに失敗しました。',
    'url' => 'The :attribute の形式が無効です。',
];
