<?php

return [
    'accepted' => 'Атрибут :attribute должен быть принят.',
    'active_url' => 'Атрибут :attribute не является допустимым URL.',
    'after' => 'Атрибут :attribute должен быть датой после :date.',
    'after_or_equal' => 'Атрибут :attribute должен быть датой после или равной :date.',
    'alpha' => 'Атрибут :attribute может содержать только буквы.',
    'alpha_dash' => 'Атрибут :attribute может содержать только буквы, цифры и тире.',
    'alpha_num' => 'Атрибут :attribute может содержать только буквы и цифры.',
    'array' => 'Атрибут :attribute должен быть массивом.',
    'before' => 'Атрибут :attribute должен быть датой до :date.',
    'before_or_equal' => 'Атрибут :attribute должен быть датой до или равной :date.',
    'between' => [
        'numeric' => 'Атрибут :attribute должен находиться между :min и :max.',
        'file' => 'Размер файла атрибута :attribute должен быть от :min до :max килобайт.',
        'string' => 'Атрибут :attribute должен содержать от :min до :max символов.',
        'array' => 'Атрибут :attribute должен содержать от :min до :max элементов.',
    ],
    'boolean' => 'Поле атрибута :attribute должно быть истиной или ложью.',
    'confirmed' => 'Подтверждение атрибута :attribute не совпадает.',
    'date' => 'Атрибут :attribute не является допустимой датой.',
    'date_format' => 'Атрибут :attribute не соответствует формату :format.',
    'different' => 'Атрибуты :attribute и :other должны быть разными.',
    'digits' => 'Атрибут :attribute должен быть :digits цифрами.',
    'digits_between' => 'Атрибут :attribute должен содержать от :min до :max цифр.',
    'dimensions' => 'Атрибут :attribute имеет недопустимые размеры изображения.',
    'distinct' => 'Поле атрибута :attribute содержит повторяющееся значение.',
    'email' => 'Атрибут :attribute должен быть действительным электронным адресом.',
    'exists' => 'Выбранный атрибут :attribute недопустим.',
    'file' => 'Атрибут :attribute должен быть файлом.',
    'filled' => 'Поле атрибута :attribute обязательно для заполнения.',
    'image' => 'Атрибут :attribute должен быть изображением.',
    'in' => 'Выбранный атрибут :attribute недопустим.',
    'in_array' => 'Поле атрибута :attribute отсутствует в :other.',
    'integer' => 'Атрибут :attribute должен быть целым числом.',
    'ip' => 'Атрибут :attribute должен быть действительным IP-адресом.',
    'json' => 'Атрибут :attribute должен быть действительной JSON строкой.',
    'max' => [
        'numeric' => 'Атрибут :attribute не может быть больше, чем :max.',
        'file' => 'Размер файла атрибута :attribute не может быть больше, чем :max килобайт.',
        'string' => 'Атрибут :attribute не может быть больше, чем :max символов.',
        'array' => 'Атрибут :attribute не может содержать более :max элементов.',
    ],
    'mimes' => 'Атрибут :attribute должен быть файлом типа: :values.',
    'mimetypes' => 'Атрибут :attribute должен быть файлом типа: :values.',
    'min' => [
        'numeric' => 'Атрибут :attribute должен быть не менее :min.',
        'file' => 'Размер файла атрибута :attribute должен быть не менее :min килобайт.',
        'string' => 'Атрибут :attribute должен содержать не менее :min символов.',
        'array' => 'Атрибут :attribute должен содержать не менее :min элементов.',
    ],
    'not_in' => 'Выбранный атрибут :attribute недопустим.',
    'numeric' => 'Атрибут :attribute должен быть числом.',
    'present' => 'Поле атрибута :attribute должно присутствовать.',
    'regex' => 'Формат атрибута :attribute недействителен.',
    'required' => 'Поле атрибута :attribute обязательно для заполнения.',
    'required_if' => 'Поле атрибута :attribute обязательно, когда :other имеет значение :value.',
    'required_unless' => 'Поле атрибута :attribute обязательно, пока :other не находится в :values.',
    'required_with' => 'Поле атрибута :attribute обязательно, когда :values присутствует.',
    'required_with_all' => 'Поле атрибута :attribute обязательно, когда все :values присутствуют.',
    'required_without' => 'Поле атрибута :attribute обязательно, когда :values отсутствует.',
    'required_without_all' => 'Поле атрибута :attribute обязательно, когда ни одно из :values не присутствует.',
    'same' => 'Атрибут :attribute и :other должны совпадать.',
    'size' => [
        'numeric' => 'Атрибут :attribute должен быть :size.',
        'file' => 'Размер файла атрибута :attribute должен быть :size килобайт.',
        'string' => 'Атрибут :attribute должен содержать :size символов.',
        'array' => 'Атрибут :attribute должен содержать :size элементов.',
    ],
    'string' => 'Атрибут :attribute должен быть строкой.',
    'timezone' => 'Атрибут :attribute должен быть допустимой временной зоной.',
    'unique' => 'Атрибут :attribute уже был взят.',
    'uploaded' => 'Атрибут :attribute не удалось загрузить.',
    'url' => 'Формат атрибута :attribute недействителен.',

    'attributes' => [],
];
